// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System.Threading.Tasks;
using KHHub.MasterDataService.IntegrationServices;
using KHHub.MasterDataService.Services.Dtos.ArticleMedia;
using Volo.Abp.Content;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;

// ReSharper disable once CheckNamespace
namespace KHHub.MasterDataService.IntegrationServices;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IArticleMediaIntegrationService), typeof(ArticleMediaIntegrationServiceClientProxy))]
public partial class ArticleMediaIntegrationServiceClientProxy : ClientProxyBase<IArticleMediaIntegrationService>, IArticleMediaIntegrationService
{
    public virtual async Task<ArticleMediaUploadResultDto> UploadImageAsync(IRemoteStreamContent content)
    {
        return await RequestAsync<ArticleMediaUploadResultDto>(nameof(UploadImageAsync), new ClientProxyRequestTypeValue
        {
            { typeof(IRemoteStreamContent), content }
        });
    }

    public virtual async Task<IRemoteStreamContent> GetAsync(string name)
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), name }
        });
    }
}
