// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using KHHub.MasterDataService.Services.Dtos.JobTags;
using KHHub.MasterDataService.Services.Dtos.Shared;
using KHHub.MasterDataService.Services.JobTags;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Content;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace KHHub.MasterDataService.Services.JobTags;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IJobTagsAppService), typeof(JobTagsClientProxy))]
public partial class JobTagsClientProxy : ClientProxyBase<IJobTagsAppService>, IJobTagsAppService
{
    public virtual async Task<PagedResultDto<JobTagDto>> GetListAsync(GetJobTagsInput input)
    {
        return await RequestAsync<PagedResultDto<JobTagDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetJobTagsInput), input }
        });
    }

    public virtual async Task<JobTagDto> GetAsync(Guid id)
    {
        return await RequestAsync<JobTagDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<JobTagDto> CreateAsync(JobTagCreateDto input)
    {
        return await RequestAsync<JobTagDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(JobTagCreateDto), input }
        });
    }

    public virtual async Task<JobTagDto> UpdateAsync(Guid id, JobTagUpdateDto input)
    {
        return await RequestAsync<JobTagDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(JobTagUpdateDto), input }
        });
    }

    public virtual async Task<IRemoteStreamContent> GetListAsExcelFileAsync(JobTagExcelDownloadDto input)
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(GetListAsExcelFileAsync), new ClientProxyRequestTypeValue
        {
            { typeof(JobTagExcelDownloadDto), input }
        });
    }

    public virtual async Task DeleteByIdsAsync(List<Guid> jobtagIds)
    {
        await RequestAsync(nameof(DeleteByIdsAsync), new ClientProxyRequestTypeValue
        {
            { typeof(List<Guid>), jobtagIds }
        });
    }

    public virtual async Task DeleteAllAsync(GetJobTagsInput input)
    {
        await RequestAsync(nameof(DeleteAllAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetJobTagsInput), input }
        });
    }

    public virtual async Task<DownloadTokenResultDto> GetDownloadTokenAsync()
    {
        return await RequestAsync<DownloadTokenResultDto>(nameof(GetDownloadTokenAsync));
    }
}
