using KHHub.MasterDataService.Services.Dtos.Shared;
using KHHub.MasterDataService.Entities.Jobs;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Permissions;
using KHHub.MasterDataService.Services.JobFavorites;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using KHHub.MasterDataService.Entities.JobFavorites;
using KHHub.MasterDataService.Services.Dtos.JobFavorites;
using KHHub.MasterDataService.Data.JobFavorites;
using KHHub.MasterDataService.Services.Dtos.Shared;

namespace KHHub.MasterDataService.Services.JobFavorites;

public class JobFavoritesAppService : JobFavoritesAppServiceBase, IJobFavoritesAppService
{
    //<suite-custom-code-autogenerated>
    public JobFavoritesAppService(IJobFavoriteRepository jobFavoriteRepository, JobFavoriteManager jobFavoriteManager, IDistributedCache<JobFavoriteDownloadTokenCacheItem, string> downloadTokenCache, IRepository<KHHub.MasterDataService.Entities.Jobs.Job, Guid> jobRepository) : base(jobFavoriteRepository, jobFavoriteManager, downloadTokenCache, jobRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}