using KHHub.MasterDataService.Entities.Places;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace KHHub.MasterDataService.Entities.PlaceFavorites;

public class PlaceFavorite : PlaceFavoriteBase
{
    //<suite-custom-code-autogenerated>
    protected PlaceFavorite()
    {
    }

    public PlaceFavorite(Guid id, Guid placeId, Guid? userId = null) : base(id, placeId, userId)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}