using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Data.PlaceFavorites;

namespace KHHub.MasterDataService.Entities.PlaceFavorites;

public class PlaceFavoriteManager : PlaceFavoriteManagerBase
{
    //<suite-custom-code-autogenerated>
    public PlaceFavoriteManager(IPlaceFavoriteRepository placeFavoriteRepository) : base(placeFavoriteRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}