using KHHub.MasterDataService.Services.Dtos.Shared;
using KHHub.MasterDataService.Entities.Wards;
using KHHub.MasterDataService.Entities.Provinces;
using KHHub.MasterDataService.Entities.PlaceCategories;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Permissions;
using KHHub.MasterDataService.Services.Places;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using KHHub.MasterDataService.Entities.Places;
using KHHub.MasterDataService.Services.Dtos.Places;
using KHHub.MasterDataService.Data.Places;
using KHHub.MasterDataService.Services.Dtos.Shared;

namespace KHHub.MasterDataService.Services.Places;

public class PlacesAppService : PlacesAppServiceBase, IPlacesAppService
{
    //<suite-custom-code-autogenerated>
    public PlacesAppService(IPlaceRepository placeRepository, PlaceManager placeManager, IDistributedCache<PlaceDownloadTokenCacheItem, string> downloadTokenCache, IRepository<KHHub.MasterDataService.Entities.PlaceCategories.PlaceCategory, Guid> placeCategoryRepository, IRepository<KHHub.MasterDataService.Entities.Provinces.Province, Guid> provinceRepository, IRepository<KHHub.MasterDataService.Entities.Wards.Ward, Guid> wardRepository) : base(placeRepository, placeManager, downloadTokenCache, placeCategoryRepository, provinceRepository, wardRepository)
    {
    }
    //</suite-custom-code-autogenerated>

    public override async Task<PagedResultDto<LookupDto<Guid>>> GetWardLookupAsync(LookupRequestDto input)
    {
        var query = (await _wardRepository.GetQueryableAsync())
            .WhereIf(!string.IsNullOrWhiteSpace(input.Filter), x => x.Name != null && x.Name.Contains(input.Filter))
            .WhereIf(input.ProvinceId.HasValue && input.ProvinceId.Value != Guid.Empty, x => x.ProvinceId == input.ProvinceId!.Value);
        var lookupData = await query.PageBy(input.SkipCount, input.MaxResultCount).ToDynamicListAsync<Ward>();
        var totalCount = query.Count();
        return new PagedResultDto<LookupDto<Guid>>
        {
            TotalCount = totalCount,
            Items = lookupData.Select(x => new LookupDto<Guid> { Id = x.Id, DisplayName = x.Name }).ToList()
        };
    }
}