using KHHub.MasterDataService.Entities.ArticleTags;
using KHHub.MasterDataService.Entities.Articles;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace KHHub.MasterDataService.Entities.ArticleTagMappings;

public class ArticleTagMapping : ArticleTagMappingBase
{
    //<suite-custom-code-autogenerated>
    protected ArticleTagMapping()
    {
    }

    public ArticleTagMapping(Guid id, Guid articleTagId, Guid articleId, bool isPrimary, int order) : base(id, articleTagId, articleId, isPrimary, order)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}