using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Data.ArticleTagMappings;

namespace KHHub.MasterDataService.Entities.ArticleTagMappings;

public class ArticleTagMappingManager : ArticleTagMappingManagerBase
{
    //<suite-custom-code-autogenerated>
    public ArticleTagMappingManager(IArticleTagMappingRepository articleTagMappingRepository) : base(articleTagMappingRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}