// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using KHHub.MasterDataService.Services.Dtos.PlaceFavorites;
using KHHub.MasterDataService.Services.Dtos.Shared;
using KHHub.MasterDataService.Services.PlaceFavorites;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Content;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace KHHub.MasterDataService.Services.PlaceFavorites;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IPlaceFavoritesAppService), typeof(PlaceFavoritesClientProxy))]
public partial class PlaceFavoritesClientProxy : ClientProxyBase<IPlaceFavoritesAppService>, IPlaceFavoritesAppService
{
    public virtual async Task<PagedResultDto<PlaceFavoriteWithNavigationPropertiesDto>> GetListAsync(GetPlaceFavoritesInput input)
    {
        return await RequestAsync<PagedResultDto<PlaceFavoriteWithNavigationPropertiesDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetPlaceFavoritesInput), input }
        });
    }

    public virtual async Task<PlaceFavoriteWithNavigationPropertiesDto> GetWithNavigationPropertiesAsync(Guid id)
    {
        return await RequestAsync<PlaceFavoriteWithNavigationPropertiesDto>(nameof(GetWithNavigationPropertiesAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PlaceFavoriteDto> GetAsync(Guid id)
    {
        return await RequestAsync<PlaceFavoriteDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PagedResultDto<LookupDto<Guid>>> GetPlaceLookupAsync(LookupRequestDto input)
    {
        return await RequestAsync<PagedResultDto<LookupDto<Guid>>>(nameof(GetPlaceLookupAsync), new ClientProxyRequestTypeValue
        {
            { typeof(LookupRequestDto), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PlaceFavoriteDto> CreateAsync(PlaceFavoriteCreateDto input)
    {
        return await RequestAsync<PlaceFavoriteDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PlaceFavoriteCreateDto), input }
        });
    }

    public virtual async Task<PlaceFavoriteDto> UpdateAsync(Guid id, PlaceFavoriteUpdateDto input)
    {
        return await RequestAsync<PlaceFavoriteDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(PlaceFavoriteUpdateDto), input }
        });
    }

    public virtual async Task<IRemoteStreamContent> GetListAsExcelFileAsync(PlaceFavoriteExcelDownloadDto input)
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(GetListAsExcelFileAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PlaceFavoriteExcelDownloadDto), input }
        });
    }

    public virtual async Task DeleteByIdsAsync(List<Guid> placefavoriteIds)
    {
        await RequestAsync(nameof(DeleteByIdsAsync), new ClientProxyRequestTypeValue
        {
            { typeof(List<Guid>), placefavoriteIds }
        });
    }

    public virtual async Task DeleteAllAsync(GetPlaceFavoritesInput input)
    {
        await RequestAsync(nameof(DeleteAllAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetPlaceFavoritesInput), input }
        });
    }

    public virtual async Task<DownloadTokenResultDto> GetDownloadTokenAsync()
    {
        return await RequestAsync<DownloadTokenResultDto>(nameof(GetDownloadTokenAsync));
    }
}
