// This file is automatically generated by ABP Suite.
namespace KHHub.MasterDataService.Entities.JobApplications;

public enum ApplicationStatus
{
    Pending = 0,
    Reviewed = 1,
    Interview = 2,
    Rejected = 3,
    Accepted = 4
}