using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace KHHub.MasterDataService.Entities.PlaceCategories;

public class PlaceCategory : PlaceCategoryBase
{
    //<suite-custom-code-autogenerated>
    protected PlaceCategory()
    {
    }

    public PlaceCategory(Guid id, string name, string slug, Guid parentId, int displayOrder, bool isActive, string? description = null, string? icon = null, string? color = null) : base(id, name, slug, parentId, displayOrder, isActive, description, icon, color)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}