using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Data.PlaceCategories;

namespace KHHub.MasterDataService.Entities.PlaceCategories;

public class PlaceCategoryManager : PlaceCategoryManagerBase
{
    //<suite-custom-code-autogenerated>
    public PlaceCategoryManager(IPlaceCategoryRepository placeCategoryRepository) : base(placeCategoryRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}