// This file is automatically generated by ABP Suite.
namespace KHHub.MasterDataService.Entities.Articles;

public enum ArticleType
{
    News = 0,
    Blog = 1,
    Guide = 2,
    Review = 3,
    Promotion = 4,
    Event = 5
}