// This file is automatically generated by ABP Suite.
namespace KHHub.MasterDataService.Entities.Articles;

public enum ArticleStatus
{
    Draft = 0,
    Pending = 1,
    Published = 2,
    Archived = 3
}