using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace KHHub.MasterDataService.Entities.Provinces;

public class Province : ProvinceBase
{
    //<suite-custom-code-autogenerated>
    protected Province()
    {
    }

    public Province(Guid id, string code, string name) : base(id, code, name)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}