using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Data.Provinces;

namespace KHHub.MasterDataService.Entities.Provinces;

public class ProvinceManager : ProvinceManagerBase
{
    //<suite-custom-code-autogenerated>
    public ProvinceManager(IProvinceRepository provinceRepository) : base(provinceRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}