// This file is automatically generated by ABP Suite.
namespace KHHub.MasterDataService.Entities.Jobs;

public enum EmploymentType
{
    FullTime = 0,
    PartTime = 1,
    Internship = 2,
    Freelance = 3,
    Contract = 4
}