// This file is automatically generated by ABP Suite.
namespace KHHub.MasterDataService.Entities.Jobs;

public enum ExperienceLevel
{
    Fresher = 0,
    Junior = 1,
    Middle = 2,
    Senior = 3,
    Lead = 4
}