// This file is automatically generated by ABP Suite.
namespace KHHub.MasterDataService.Entities.Jobs;

public enum JobStatus
{
    Draft = 0,
    Published = 1,
    Closed = 2,
    Expired = 3,
    Archived = 4
}