using KHHub.MasterDataService.Services.Dtos.Shared;
using KHHub.MasterDataService.Entities.Places;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Permissions;
using KHHub.MasterDataService.Services.PlaceViews;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using KHHub.MasterDataService.Entities.PlaceViews;
using KHHub.MasterDataService.Services.Dtos.PlaceViews;
using KHHub.MasterDataService.Data.PlaceViews;
using KHHub.MasterDataService.Services.Dtos.Shared;

namespace KHHub.MasterDataService.Services.PlaceViews;

public class PlaceViewsAppService : PlaceViewsAppServiceBase, IPlaceViewsAppService
{
    //<suite-custom-code-autogenerated>
    public PlaceViewsAppService(IPlaceViewRepository placeViewRepository, PlaceViewManager placeViewManager, IDistributedCache<PlaceViewDownloadTokenCacheItem, string> downloadTokenCache, IRepository<KHHub.MasterDataService.Entities.Places.Place, Guid> placeRepository) : base(placeViewRepository, placeViewManager, downloadTokenCache, placeRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}