using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Permissions;
using KHHub.MasterDataService.Services.JobTags;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using KHHub.MasterDataService.Entities.JobTags;
using KHHub.MasterDataService.Services.Dtos.JobTags;
using KHHub.MasterDataService.Data.JobTags;
using KHHub.MasterDataService.Services.Dtos.Shared;

namespace KHHub.MasterDataService.Services.JobTags;

public class JobTagsAppService : JobTagsAppServiceBase, IJobTagsAppService
{
    //<suite-custom-code-autogenerated>
    public JobTagsAppService(IJobTagRepository jobTagRepository, JobTagManager jobTagManager, IDistributedCache<JobTagDownloadTokenCacheItem, string> downloadTokenCache) : base(jobTagRepository, jobTagManager, downloadTokenCache)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}