using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Permissions;
using KHHub.MasterDataService.Services.ArticleTags;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using KHHub.MasterDataService.Entities.ArticleTags;
using KHHub.MasterDataService.Services.Dtos.ArticleTags;
using KHHub.MasterDataService.Data.ArticleTags;
using KHHub.MasterDataService.Services.Dtos.Shared;

namespace KHHub.MasterDataService.Services.ArticleTags;

public class ArticleTagsAppService : ArticleTagsAppServiceBase, IArticleTagsAppService
{
    //<suite-custom-code-autogenerated>
    public ArticleTagsAppService(IArticleTagRepository articleTagRepository, ArticleTagManager articleTagManager, IDistributedCache<ArticleTagDownloadTokenCacheItem, string> downloadTokenCache) : base(articleTagRepository, articleTagManager, downloadTokenCache)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}