using KHHub.MasterDataService.Services.Dtos.Shared;
using KHHub.MasterDataService.Data.PlaceCategories;
using KHHub.MasterDataService.Services.Dtos.PlaceCategories;
using KHHub.MasterDataService.Entities.PlaceCategories;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Permissions;
using KHHub.MasterDataService.Services.PlaceCategories;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using KHHub.MasterDataService.Entities.PlaceCategories;
using KHHub.MasterDataService.Services.Dtos.PlaceCategories;
using KHHub.MasterDataService.Data.PlaceCategories;
using KHHub.MasterDataService.Services.Dtos.Shared;

namespace KHHub.MasterDataService.Services.PlaceCategories;

public class PlaceCategoriesAppService : PlaceCategoriesAppServiceBase, IPlaceCategoriesAppService
{
    //<suite-custom-code-autogenerated>
    public PlaceCategoriesAppService(IPlaceCategoryRepository placeCategoryRepository, PlaceCategoryManager placeCategoryManager, IDistributedCache<PlaceCategoryDownloadTokenCacheItem, string> downloadTokenCache) : base(placeCategoryRepository, placeCategoryManager, downloadTokenCache)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}