using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Data.ArticleCategories;

namespace KHHub.MasterDataService.Entities.ArticleCategories;

public class ArticleCategoryManager : ArticleCategoryManagerBase
{
    //<suite-custom-code-autogenerated>
    public ArticleCategoryManager(IArticleCategoryRepository articleCategoryRepository) : base(articleCategoryRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}