using KHHub.MasterDataService.Services.Dtos.Shared;
using KHHub.MasterDataService.Entities.ArticleCategories;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Permissions;
using KHHub.MasterDataService.Services.Articles;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using KHHub.MasterDataService.Entities.Articles;
using KHHub.MasterDataService.Services.Dtos.Articles;
using KHHub.MasterDataService.Data.Articles;
using KHHub.MasterDataService.Services.Dtos.Shared;

namespace KHHub.MasterDataService.Services.Articles;

public class ArticlesAppService : ArticlesAppServiceBase, IArticlesAppService
{
    //<suite-custom-code-autogenerated>
    public ArticlesAppService(IArticleRepository articleRepository, ArticleManager articleManager, IDistributedCache<ArticleDownloadTokenCacheItem, string> downloadTokenCache, IRepository<KHHub.MasterDataService.Entities.ArticleCategories.ArticleCategory, Guid> articleCategoryRepository) : base(articleRepository, articleManager, downloadTokenCache, articleCategoryRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}