// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using KHHub.MasterDataService.Services.Dtos.HomeBanners;
using KHHub.MasterDataService.Services.Dtos.Shared;
using KHHub.MasterDataService.Services.HomeBanners;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Content;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace KHHub.MasterDataService.Services.HomeBanners;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IHomeBannersAppService), typeof(HomeBannersClientProxy))]
public partial class HomeBannersClientProxy : ClientProxyBase<IHomeBannersAppService>, IHomeBannersAppService
{
    public virtual async Task<PagedResultDto<HomeBannerDto>> GetListAsync(GetHomeBannersInput input)
    {
        return await RequestAsync<PagedResultDto<HomeBannerDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetHomeBannersInput), input }
        });
    }

    public virtual async Task<HomeBannerDto> GetAsync(Guid id)
    {
        return await RequestAsync<HomeBannerDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<HomeBannerDto> CreateAsync(HomeBannerCreateDto input)
    {
        return await RequestAsync<HomeBannerDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(HomeBannerCreateDto), input }
        });
    }

    public virtual async Task<HomeBannerDto> UpdateAsync(Guid id, HomeBannerUpdateDto input)
    {
        return await RequestAsync<HomeBannerDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(HomeBannerUpdateDto), input }
        });
    }

    public virtual async Task<IRemoteStreamContent> GetListAsExcelFileAsync(HomeBannerExcelDownloadDto input)
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(GetListAsExcelFileAsync), new ClientProxyRequestTypeValue
        {
            { typeof(HomeBannerExcelDownloadDto), input }
        });
    }

    public virtual async Task DeleteByIdsAsync(List<Guid> homebannerIds)
    {
        await RequestAsync(nameof(DeleteByIdsAsync), new ClientProxyRequestTypeValue
        {
            { typeof(List<Guid>), homebannerIds }
        });
    }

    public virtual async Task DeleteAllAsync(GetHomeBannersInput input)
    {
        await RequestAsync(nameof(DeleteAllAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetHomeBannersInput), input }
        });
    }

    public virtual async Task<DownloadTokenResultDto> GetDownloadTokenAsync()
    {
        return await RequestAsync<DownloadTokenResultDto>(nameof(GetDownloadTokenAsync));
    }
}
