// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using KHHub.MasterDataService.Services.ArticleTagMappings;
using KHHub.MasterDataService.Services.Dtos.ArticleTagMappings;
using KHHub.MasterDataService.Services.Dtos.Shared;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Content;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace KHHub.MasterDataService.Services.ArticleTagMappings;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IArticleTagMappingsAppService), typeof(ArticleTagMappingsClientProxy))]
public partial class ArticleTagMappingsClientProxy : ClientProxyBase<IArticleTagMappingsAppService>, IArticleTagMappingsAppService
{
    public virtual async Task<PagedResultDto<LookupDto<Guid>>> GetArticleTagLookupAsync(LookupRequestDto input)
    {
        return await RequestAsync<PagedResultDto<LookupDto<Guid>>>(nameof(GetArticleTagLookupAsync), new ClientProxyRequestTypeValue
        {
            { typeof(LookupRequestDto), input }
        });
    }

    public virtual async Task<PagedResultDto<ArticleTagMappingWithNavigationPropertiesDto>> GetListAsync(GetArticleTagMappingsInput input)
    {
        return await RequestAsync<PagedResultDto<ArticleTagMappingWithNavigationPropertiesDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetArticleTagMappingsInput), input }
        });
    }

    public virtual async Task<ArticleTagMappingWithNavigationPropertiesDto> GetWithNavigationPropertiesAsync(Guid id)
    {
        return await RequestAsync<ArticleTagMappingWithNavigationPropertiesDto>(nameof(GetWithNavigationPropertiesAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<ArticleTagMappingDto> GetAsync(Guid id)
    {
        return await RequestAsync<ArticleTagMappingDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PagedResultDto<LookupDto<Guid>>> GetArticleLookupAsync(LookupRequestDto input)
    {
        return await RequestAsync<PagedResultDto<LookupDto<Guid>>>(nameof(GetArticleLookupAsync), new ClientProxyRequestTypeValue
        {
            { typeof(LookupRequestDto), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<ArticleTagMappingDto> CreateAsync(ArticleTagMappingCreateDto input)
    {
        return await RequestAsync<ArticleTagMappingDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ArticleTagMappingCreateDto), input }
        });
    }

    public virtual async Task<ArticleTagMappingDto> UpdateAsync(Guid id, ArticleTagMappingUpdateDto input)
    {
        return await RequestAsync<ArticleTagMappingDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(ArticleTagMappingUpdateDto), input }
        });
    }

    public virtual async Task<IRemoteStreamContent> GetListAsExcelFileAsync(ArticleTagMappingExcelDownloadDto input)
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(GetListAsExcelFileAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ArticleTagMappingExcelDownloadDto), input }
        });
    }

    public virtual async Task DeleteByIdsAsync(List<Guid> articletagmappingIds)
    {
        await RequestAsync(nameof(DeleteByIdsAsync), new ClientProxyRequestTypeValue
        {
            { typeof(List<Guid>), articletagmappingIds }
        });
    }

    public virtual async Task DeleteAllAsync(GetArticleTagMappingsInput input)
    {
        await RequestAsync(nameof(DeleteAllAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetArticleTagMappingsInput), input }
        });
    }

    public virtual async Task<DownloadTokenResultDto> GetDownloadTokenAsync()
    {
        return await RequestAsync<DownloadTokenResultDto>(nameof(GetDownloadTokenAsync));
    }
}
