using KHHub.MasterDataService.Services.Dtos.Shared;
using KHHub.MasterDataService.Entities.MediaFiles;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Permissions;
using KHHub.MasterDataService.Services.EntityFiles;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using KHHub.MasterDataService.Entities.EntityFiles;
using KHHub.MasterDataService.Services.Dtos.EntityFiles;
using KHHub.MasterDataService.Data.EntityFiles;
using KHHub.MasterDataService.Services.Dtos.MediaFiles;
using KHHub.MasterDataService.Services.MediaFiles;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Options;

namespace KHHub.MasterDataService.Services.EntityFiles;

public class EntityFilesAppService : EntityFilesAppServiceBase, IEntityFilesAppService
{
    private readonly IOptionsSnapshot<MediaFilesStorageOptions> _mediaStorageOptions;
    private readonly IConfiguration _configuration;
    private readonly IMinioBlobReadUrlSigner _minioBlobReadUrlSigner;

    //<suite-custom-code-autogenerated>
    public EntityFilesAppService(
        IEntityFileRepository entityFileRepository,
        EntityFileManager entityFileManager,
        IDistributedCache<EntityFileDownloadTokenCacheItem, string> downloadTokenCache,
        IRepository<KHHub.MasterDataService.Entities.MediaFiles.MediaFile, Guid> mediaFileRepository,
        IOptionsSnapshot<MediaFilesStorageOptions> mediaStorageOptions,
        IConfiguration configuration,
        IMinioBlobReadUrlSigner minioBlobReadUrlSigner)
        : base(entityFileRepository, entityFileManager, downloadTokenCache, mediaFileRepository)
    {
        _mediaStorageOptions = mediaStorageOptions;
        _configuration = configuration;
        _minioBlobReadUrlSigner = minioBlobReadUrlSigner;
    }
    //</suite-custom-code-autogenerated>

    public override async Task<PagedResultDto<EntityFileWithNavigationPropertiesDto>> GetListAsync(GetEntityFilesInput input)
    {
        var result = await base.GetListAsync(input);
        foreach (var item in result.Items)
        {
            await EnrichNestedMediaFileDtoAsync(item?.MediaFile).ConfigureAwait(false);
        }

        return result;
    }

    public override async Task<EntityFileWithNavigationPropertiesDto> GetWithNavigationPropertiesAsync(Guid id)
    {
        var dto = await base.GetWithNavigationPropertiesAsync(id);
        await EnrichNestedMediaFileDtoAsync(dto?.MediaFile).ConfigureAwait(false);
        return dto;
    }

    /// <summary>
    /// Align nested media with explorer: stable public path and presigned absolute URL when MinIO denies anonymous GET.
    /// </summary>
    private async Task EnrichNestedMediaFileDtoAsync(MediaFileDto? mediaFile)
    {
        if (mediaFile == null || string.IsNullOrWhiteSpace(mediaFile.Path))
        {
            return;
        }

        mediaFile.PublicPath = MediaExplorerPathHelper.BuildStablePublicPath(
            _mediaStorageOptions.Value.PublicBaseUrl,
            mediaFile.Path);

        if (_mediaStorageOptions.Value.UsePresignedReadUrls)
        {
            await TryAttachPresignedReadUrlAsync(mediaFile).ConfigureAwait(false);
        }
    }

    private async Task TryAttachPresignedReadUrlAsync(MediaFileDto dto)
    {
        if (dto.FileType == FileType.Folder)
        {
            return;
        }

        if (string.IsNullOrWhiteSpace(dto.Path))
        {
            return;
        }

        if (!(string.Equals(dto.StorageProvider, "Minio", StringComparison.OrdinalIgnoreCase)
              || string.IsNullOrWhiteSpace(dto.StorageProvider)))
        {
            return;
        }

        var defaultBucket = _configuration["BlobStoring:Minio:BucketName"];
        var bucket = (dto.Bucket ?? defaultBucket)?.Trim();

        if (string.IsNullOrWhiteSpace(bucket))
        {
            return;
        }

        var expiry = _mediaStorageOptions.Value.PresignedReadExpirySeconds;
        var signed = await _minioBlobReadUrlSigner.TryGetPresignedReadUrlAsync(bucket!, dto.Path!, expiry)
            .ConfigureAwait(false);

        if (!string.IsNullOrWhiteSpace(signed))
        {
            dto.Url = signed;
        }
    }
}