using KHHub.MasterDataService.Services.Dtos.Shared;
using KHHub.MasterDataService.Entities.MediaFiles;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Permissions;
using KHHub.MasterDataService.Services.EntityFiles;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using KHHub.MasterDataService.Entities.EntityFiles;
using KHHub.MasterDataService.Services.Dtos.EntityFiles;
using KHHub.MasterDataService.Data.EntityFiles;
using KHHub.MasterDataService.Services.Dtos.Shared;

namespace KHHub.MasterDataService.Services.EntityFiles;

public class EntityFilesAppService : EntityFilesAppServiceBase, IEntityFilesAppService
{
    //<suite-custom-code-autogenerated>
    public EntityFilesAppService(IEntityFileRepository entityFileRepository, EntityFileManager entityFileManager, IDistributedCache<EntityFileDownloadTokenCacheItem, string> downloadTokenCache, IRepository<KHHub.MasterDataService.Entities.MediaFiles.MediaFile, Guid> mediaFileRepository) : base(entityFileRepository, entityFileManager, downloadTokenCache, mediaFileRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}