using KHHub.MasterDataService.Entities.JobApplications;
using KHHub.MasterDataService.Entities.Jobs;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace KHHub.MasterDataService.Entities.JobApplications;

public class JobApplication : JobApplicationBase
{
    //<suite-custom-code-autogenerated>
    protected JobApplication()
    {
    }

    public JobApplication(Guid id, Guid jobId, string fullName, DateTime appliedAt, ApplicationStatus status, Guid? userId = null, string? email = null, string? phoneNumber = null, string? cvUrl = null, string? portfolioUrl = null) : base(id, jobId, fullName, appliedAt, status, userId, email, phoneNumber, cvUrl, portfolioUrl)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}