using KHHub.MasterDataService.Entities.JobApplications;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Data.JobApplications;

namespace KHHub.MasterDataService.Entities.JobApplications;

public class JobApplicationManager : JobApplicationManagerBase
{
    //<suite-custom-code-autogenerated>
    public JobApplicationManager(IJobApplicationRepository jobApplicationRepository) : base(jobApplicationRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}