// This file is automatically generated by ABP Suite.
namespace KHHub.MasterDataService.Entities.Places;

public enum PlaceStatus
{
    Draft = 0,
    Published = 1,
    Hidden = 2,
    Archived = 3
}