// This file is automatically generated by ABP Suite.
namespace KHHub.MasterDataService.Entities.Places;

public enum PriceRange
{
    Free = 0,
    Cheap = 1,
    Medium = 2,
    High = 3,
    Luxury = 4
}