using KHHub.MasterDataService.Entities.JobTags;
using KHHub.MasterDataService.Entities.Jobs;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace KHHub.MasterDataService.Entities.JobTagMappings;

public class JobTagMapping : JobTagMappingBase
{
    //<suite-custom-code-autogenerated>
    protected JobTagMapping()
    {
    }

    public JobTagMapping(Guid id, Guid jobTagId, Guid jobId, bool isPrimary, string? sortOrder = null) : base(id, jobTagId, jobId, isPrimary, sortOrder)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}