using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Data.JobTagMappings;

namespace KHHub.MasterDataService.Entities.JobTagMappings;

public class JobTagMappingManager : JobTagMappingManagerBase
{
    //<suite-custom-code-autogenerated>
    public JobTagMappingManager(IJobTagMappingRepository jobTagMappingRepository) : base(jobTagMappingRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}