// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using KHHub.MasterDataService.Services.Dtos.PlaceTagMappings;
using KHHub.MasterDataService.Services.Dtos.Shared;
using KHHub.MasterDataService.Services.PlaceTagMappings;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Content;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace KHHub.MasterDataService.Services.PlaceTagMappings;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IPlaceTagMappingsAppService), typeof(PlaceTagMappingsClientProxy))]
public partial class PlaceTagMappingsClientProxy : ClientProxyBase<IPlaceTagMappingsAppService>, IPlaceTagMappingsAppService
{
    public virtual async Task<PagedResultDto<PlaceTagMappingWithNavigationPropertiesDto>> GetListAsync(GetPlaceTagMappingsInput input)
    {
        return await RequestAsync<PagedResultDto<PlaceTagMappingWithNavigationPropertiesDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetPlaceTagMappingsInput), input }
        });
    }

    public virtual async Task<PlaceTagMappingWithNavigationPropertiesDto> GetWithNavigationPropertiesAsync(Guid id)
    {
        return await RequestAsync<PlaceTagMappingWithNavigationPropertiesDto>(nameof(GetWithNavigationPropertiesAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PlaceTagMappingDto> GetAsync(Guid id)
    {
        return await RequestAsync<PlaceTagMappingDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PagedResultDto<LookupDto<Guid>>> GetPlaceTagLookupAsync(LookupRequestDto input)
    {
        return await RequestAsync<PagedResultDto<LookupDto<Guid>>>(nameof(GetPlaceTagLookupAsync), new ClientProxyRequestTypeValue
        {
            { typeof(LookupRequestDto), input }
        });
    }

    public virtual async Task<PagedResultDto<LookupDto<Guid>>> GetPlaceLookupAsync(LookupRequestDto input)
    {
        return await RequestAsync<PagedResultDto<LookupDto<Guid>>>(nameof(GetPlaceLookupAsync), new ClientProxyRequestTypeValue
        {
            { typeof(LookupRequestDto), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PlaceTagMappingDto> CreateAsync(PlaceTagMappingCreateDto input)
    {
        return await RequestAsync<PlaceTagMappingDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PlaceTagMappingCreateDto), input }
        });
    }

    public virtual async Task<PlaceTagMappingDto> UpdateAsync(Guid id, PlaceTagMappingUpdateDto input)
    {
        return await RequestAsync<PlaceTagMappingDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(PlaceTagMappingUpdateDto), input }
        });
    }

    public virtual async Task<IRemoteStreamContent> GetListAsExcelFileAsync(PlaceTagMappingExcelDownloadDto input)
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(GetListAsExcelFileAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PlaceTagMappingExcelDownloadDto), input }
        });
    }

    public virtual async Task DeleteByIdsAsync(List<Guid> placetagmappingIds)
    {
        await RequestAsync(nameof(DeleteByIdsAsync), new ClientProxyRequestTypeValue
        {
            { typeof(List<Guid>), placetagmappingIds }
        });
    }

    public virtual async Task DeleteAllAsync(GetPlaceTagMappingsInput input)
    {
        await RequestAsync(nameof(DeleteAllAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetPlaceTagMappingsInput), input }
        });
    }

    public virtual async Task<DownloadTokenResultDto> GetDownloadTokenAsync()
    {
        return await RequestAsync<DownloadTokenResultDto>(nameof(GetDownloadTokenAsync));
    }
}
