using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Permissions;
using KHHub.MasterDataService.Services.PlaceTags;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using KHHub.MasterDataService.Entities.PlaceTags;
using KHHub.MasterDataService.Services.Dtos.PlaceTags;
using KHHub.MasterDataService.Data.PlaceTags;
using KHHub.MasterDataService.Services.Dtos.Shared;

namespace KHHub.MasterDataService.Services.PlaceTags;

public class PlaceTagsAppService : PlaceTagsAppServiceBase, IPlaceTagsAppService
{
    //<suite-custom-code-autogenerated>
    public PlaceTagsAppService(IPlaceTagRepository placeTagRepository, PlaceTagManager placeTagManager, IDistributedCache<PlaceTagDownloadTokenCacheItem, string> downloadTokenCache) : base(placeTagRepository, placeTagManager, downloadTokenCache)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}