// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using KHHub.MasterDataService.Services.Dtos.JobFavorites;
using KHHub.MasterDataService.Services.Dtos.Shared;
using KHHub.MasterDataService.Services.JobFavorites;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Content;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace KHHub.MasterDataService.Services.JobFavorites;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IJobFavoritesAppService), typeof(JobFavoritesClientProxy))]
public partial class JobFavoritesClientProxy : ClientProxyBase<IJobFavoritesAppService>, IJobFavoritesAppService
{
    public virtual async Task<PagedResultDto<JobFavoriteWithNavigationPropertiesDto>> GetListAsync(GetJobFavoritesInput input)
    {
        return await RequestAsync<PagedResultDto<JobFavoriteWithNavigationPropertiesDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetJobFavoritesInput), input }
        });
    }

    public virtual async Task<JobFavoriteWithNavigationPropertiesDto> GetWithNavigationPropertiesAsync(Guid id)
    {
        return await RequestAsync<JobFavoriteWithNavigationPropertiesDto>(nameof(GetWithNavigationPropertiesAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<JobFavoriteDto> GetAsync(Guid id)
    {
        return await RequestAsync<JobFavoriteDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PagedResultDto<LookupDto<Guid>>> GetJobLookupAsync(LookupRequestDto input)
    {
        return await RequestAsync<PagedResultDto<LookupDto<Guid>>>(nameof(GetJobLookupAsync), new ClientProxyRequestTypeValue
        {
            { typeof(LookupRequestDto), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<JobFavoriteDto> CreateAsync(JobFavoriteCreateDto input)
    {
        return await RequestAsync<JobFavoriteDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(JobFavoriteCreateDto), input }
        });
    }

    public virtual async Task<JobFavoriteDto> UpdateAsync(Guid id, JobFavoriteUpdateDto input)
    {
        return await RequestAsync<JobFavoriteDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(JobFavoriteUpdateDto), input }
        });
    }

    public virtual async Task<IRemoteStreamContent> GetListAsExcelFileAsync(JobFavoriteExcelDownloadDto input)
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(GetListAsExcelFileAsync), new ClientProxyRequestTypeValue
        {
            { typeof(JobFavoriteExcelDownloadDto), input }
        });
    }

    public virtual async Task DeleteByIdsAsync(List<Guid> jobfavoriteIds)
    {
        await RequestAsync(nameof(DeleteByIdsAsync), new ClientProxyRequestTypeValue
        {
            { typeof(List<Guid>), jobfavoriteIds }
        });
    }

    public virtual async Task DeleteAllAsync(GetJobFavoritesInput input)
    {
        await RequestAsync(nameof(DeleteAllAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetJobFavoritesInput), input }
        });
    }

    public virtual async Task<DownloadTokenResultDto> GetDownloadTokenAsync()
    {
        return await RequestAsync<DownloadTokenResultDto>(nameof(GetDownloadTokenAsync));
    }
}
