using KHHub.MasterDataService.Services.Dtos.Shared;
using KHHub.MasterDataService.Entities.Jobs;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Permissions;
using KHHub.MasterDataService.Services.JobApplications;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using KHHub.MasterDataService.Entities.JobApplications;
using KHHub.MasterDataService.Services.Dtos.JobApplications;
using KHHub.MasterDataService.Data.JobApplications;
using KHHub.MasterDataService.Services.Dtos.Shared;

namespace KHHub.MasterDataService.Services.JobApplications;

public class JobApplicationsAppService : JobApplicationsAppServiceBase, IJobApplicationsAppService
{
    //<suite-custom-code-autogenerated>
    public JobApplicationsAppService(IJobApplicationRepository jobApplicationRepository, JobApplicationManager jobApplicationManager, IDistributedCache<JobApplicationDownloadTokenCacheItem, string> downloadTokenCache, IRepository<KHHub.MasterDataService.Entities.Jobs.Job, Guid> jobRepository) : base(jobApplicationRepository, jobApplicationManager, downloadTokenCache, jobRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}