// This file is automatically generated by ABP Suite.
namespace KHHub.MasterDataService.Entities.MediaFiles;

public enum FileType
{
    Image = 0,
    Video = 1,
    Document = 2,
    Avatar = 3,
    Thumbnail = 4,
    Gallery = 5
}