// This file is automatically generated by ABP Suite.
namespace KHHub.MasterDataService.Entities.MediaFiles;

public enum FileStatus
{
    Uploading = 0,
    Ready = 1,
    Failed = 2,
    Deleted = 3
}