using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Data.JobCategories;

namespace KHHub.MasterDataService.Entities.JobCategories;

public class JobCategoryManager : JobCategoryManagerBase
{
    //<suite-custom-code-autogenerated>
    public JobCategoryManager(IJobCategoryRepository jobCategoryRepository) : base(jobCategoryRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}