using KHHub.MasterDataService.Services.Dtos.Shared;
using KHHub.MasterDataService.Entities.Articles;
using KHHub.MasterDataService.Entities.ArticleTags;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Permissions;
using KHHub.MasterDataService.Services.ArticleTagMappings;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using KHHub.MasterDataService.Entities.ArticleTagMappings;
using KHHub.MasterDataService.Services.Dtos.ArticleTagMappings;
using KHHub.MasterDataService.Data.ArticleTagMappings;
using KHHub.MasterDataService.Services.Dtos.Shared;

namespace KHHub.MasterDataService.Services.ArticleTagMappings;

public class ArticleTagMappingsAppService : ArticleTagMappingsAppServiceBase, IArticleTagMappingsAppService
{
    //<suite-custom-code-autogenerated>
    public ArticleTagMappingsAppService(IArticleTagMappingRepository articleTagMappingRepository, ArticleTagMappingManager articleTagMappingManager, IDistributedCache<ArticleTagMappingDownloadTokenCacheItem, string> downloadTokenCache, IRepository<KHHub.MasterDataService.Entities.ArticleTags.ArticleTag, Guid> articleTagRepository, IRepository<KHHub.MasterDataService.Entities.Articles.Article, Guid> articleRepository) : base(articleTagMappingRepository, articleTagMappingManager, downloadTokenCache, articleTagRepository, articleRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}