// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using KHHub.MasterDataService.Services.Dtos.JobViews;
using KHHub.MasterDataService.Services.Dtos.Shared;
using KHHub.MasterDataService.Services.JobViews;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Content;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace KHHub.MasterDataService.Services.JobViews;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IJobViewsAppService), typeof(JobViewsClientProxy))]
public partial class JobViewsClientProxy : ClientProxyBase<IJobViewsAppService>, IJobViewsAppService
{
    public virtual async Task<PagedResultDto<JobViewWithNavigationPropertiesDto>> GetListAsync(GetJobViewsInput input)
    {
        return await RequestAsync<PagedResultDto<JobViewWithNavigationPropertiesDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetJobViewsInput), input }
        });
    }

    public virtual async Task<JobViewWithNavigationPropertiesDto> GetWithNavigationPropertiesAsync(Guid id)
    {
        return await RequestAsync<JobViewWithNavigationPropertiesDto>(nameof(GetWithNavigationPropertiesAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<JobViewDto> GetAsync(Guid id)
    {
        return await RequestAsync<JobViewDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PagedResultDto<LookupDto<Guid>>> GetJobLookupAsync(LookupRequestDto input)
    {
        return await RequestAsync<PagedResultDto<LookupDto<Guid>>>(nameof(GetJobLookupAsync), new ClientProxyRequestTypeValue
        {
            { typeof(LookupRequestDto), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<JobViewDto> CreateAsync(JobViewCreateDto input)
    {
        return await RequestAsync<JobViewDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(JobViewCreateDto), input }
        });
    }

    public virtual async Task<JobViewDto> UpdateAsync(Guid id, JobViewUpdateDto input)
    {
        return await RequestAsync<JobViewDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(JobViewUpdateDto), input }
        });
    }

    public virtual async Task<IRemoteStreamContent> GetListAsExcelFileAsync(JobViewExcelDownloadDto input)
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(GetListAsExcelFileAsync), new ClientProxyRequestTypeValue
        {
            { typeof(JobViewExcelDownloadDto), input }
        });
    }

    public virtual async Task DeleteByIdsAsync(List<Guid> jobviewIds)
    {
        await RequestAsync(nameof(DeleteByIdsAsync), new ClientProxyRequestTypeValue
        {
            { typeof(List<Guid>), jobviewIds }
        });
    }

    public virtual async Task DeleteAllAsync(GetJobViewsInput input)
    {
        await RequestAsync(nameof(DeleteAllAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetJobViewsInput), input }
        });
    }

    public virtual async Task<DownloadTokenResultDto> GetDownloadTokenAsync()
    {
        return await RequestAsync<DownloadTokenResultDto>(nameof(GetDownloadTokenAsync));
    }
}
