using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Permissions;
using KHHub.MasterDataService.Services.MediaFiles;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using KHHub.MasterDataService.Entities.MediaFiles;
using KHHub.MasterDataService.Services.Dtos.MediaFiles;
using KHHub.MasterDataService.Data.MediaFiles;
using KHHub.MasterDataService.Services.Dtos.Shared;

namespace KHHub.MasterDataService.Services.MediaFiles;

public class MediaFilesAppService : MediaFilesAppServiceBase, IMediaFilesAppService
{
    //<suite-custom-code-autogenerated>
    public MediaFilesAppService(IMediaFileRepository mediaFileRepository, MediaFileManager mediaFileManager, IDistributedCache<MediaFileDownloadTokenCacheItem, string> downloadTokenCache) : base(mediaFileRepository, mediaFileManager, downloadTokenCache)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}