using KHHub.MasterDataService.Entities.Jobs;
using KHHub.MasterDataService.Entities.Provinces;
using KHHub.MasterDataService.Entities.Wards;
using KHHub.MasterDataService.Entities.JobCategories;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace KHHub.MasterDataService.Entities.Jobs;

public class Job : JobBase
{
    //<suite-custom-code-autogenerated>
    protected Job()
    {
    }

    public Job(Guid id, Guid provinceId, Guid wardId, Guid jobCategoryId, string title, string slug, JobStatus status, int viewCount, int applicationCount, int favoriteCount, int shareCount, bool isFeatured, bool isUrgent, bool isHot, string seoTitle, string? summary = null, string? description = null, string? requirements = null, string? benefits = null, string? thumbnailUrl = null, string? coverImageUrl = null, EmploymentType? employmentType = null, WorkMode? workMode = null, ExperienceLevel? experienceLevel = null, decimal? salaryMin = null, decimal? salaryMax = null, string? salaryText = null, string? salaryCurrency = null, string? location = null, string? contactEmail = null, string? contactPhone = null, string? applicationUrl = null, DateTime? publishedAt = null, string? seoDescription = null, string? seoKeywords = null) : base(id, provinceId, wardId, jobCategoryId, title, slug, status, viewCount, applicationCount, favoriteCount, shareCount, isFeatured, isUrgent, isHot, seoTitle, summary, description, requirements, benefits, thumbnailUrl, coverImageUrl, employmentType, workMode, experienceLevel, salaryMin, salaryMax, salaryText, salaryCurrency, location, contactEmail, contactPhone, applicationUrl, publishedAt, seoDescription, seoKeywords)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}