using KHHub.MasterDataService.Entities.Jobs;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Data.Jobs;

namespace KHHub.MasterDataService.Entities.Jobs;

public class JobManager : JobManagerBase
{
    //<suite-custom-code-autogenerated>
    public JobManager(IJobRepository jobRepository) : base(jobRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}