using KHHub.MasterDataService.Entities.Places;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Data.Places;

namespace KHHub.MasterDataService.Entities.Places;

public class PlaceManager : PlaceManagerBase
{
    //<suite-custom-code-autogenerated>
    public PlaceManager(IPlaceRepository placeRepository) : base(placeRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}