using KHHub.MasterDataService.Entities.Places;
using KHHub.MasterDataService.Entities.PlaceCategories;
using KHHub.MasterDataService.Entities.Provinces;
using KHHub.MasterDataService.Entities.Wards;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace KHHub.MasterDataService.Entities.Places;

public class Place : PlaceBase
{
    //<suite-custom-code-autogenerated>
    protected Place()
    {
    }

    public Place(Guid id, Guid placeCategoryId, Guid provinceId, Guid wardId, string name, string slug, decimal latitude, decimal longituded, PriceRange priceRange, PlaceStatus status, int viewCount, int favoriteCount, int reviewCount, decimal ratingAveraged, int ratingTotal, bool isFeatured, bool isHot, bool isVerified, string seoTitle, string? shortDescription = null, string? description = null, string? thumbnailUrl = null, string? coverImageUrl = null, string? address = null, string? phoneNumber = null, string? email = null, string? website = null, string? openingHours = null, string? googleMapUrl = null, string? seoDescription = null, string? seoKeywords = null) : base(id, placeCategoryId, provinceId, wardId, name, slug, latitude, longituded, priceRange, status, viewCount, favoriteCount, reviewCount, ratingAveraged, ratingTotal, isFeatured, isHot, isVerified, seoTitle, shortDescription, description, thumbnailUrl, coverImageUrl, address, phoneNumber, email, website, openingHours, googleMapUrl, seoDescription, seoKeywords)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}