// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using KHHub.MasterDataService.Services.Dtos.MediaFiles;
using KHHub.MasterDataService.Services.Dtos.Shared;
using KHHub.MasterDataService.Services.MediaFiles;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Content;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace KHHub.MasterDataService.Services.MediaFiles;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IMediaFilesAppService), typeof(MediaFilesClientProxy))]
public partial class MediaFilesClientProxy : ClientProxyBase<IMediaFilesAppService>, IMediaFilesAppService
{
    public virtual async Task<PagedResultDto<MediaFileDto>> GetListAsync(GetMediaFilesInput input)
    {
        return await RequestAsync<PagedResultDto<MediaFileDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetMediaFilesInput), input }
        });
    }

    public virtual async Task<MediaFileDto> GetAsync(Guid id)
    {
        return await RequestAsync<MediaFileDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<MediaFileDto> CreateAsync(MediaFileCreateDto input)
    {
        return await RequestAsync<MediaFileDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(MediaFileCreateDto), input }
        });
    }

    public virtual async Task<MediaFileDto> UpdateAsync(Guid id, MediaFileUpdateDto input)
    {
        return await RequestAsync<MediaFileDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(MediaFileUpdateDto), input }
        });
    }

    public virtual async Task<IRemoteStreamContent> GetListAsExcelFileAsync(MediaFileExcelDownloadDto input)
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(GetListAsExcelFileAsync), new ClientProxyRequestTypeValue
        {
            { typeof(MediaFileExcelDownloadDto), input }
        });
    }

    public virtual async Task DeleteByIdsAsync(List<Guid> mediafileIds)
    {
        await RequestAsync(nameof(DeleteByIdsAsync), new ClientProxyRequestTypeValue
        {
            { typeof(List<Guid>), mediafileIds }
        });
    }

    public virtual async Task DeleteAllAsync(GetMediaFilesInput input)
    {
        await RequestAsync(nameof(DeleteAllAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetMediaFilesInput), input }
        });
    }

    public virtual async Task<DownloadTokenResultDto> GetDownloadTokenAsync()
    {
        return await RequestAsync<DownloadTokenResultDto>(nameof(GetDownloadTokenAsync));
    }
}
