using KHHub.MasterDataService.Entities.HomeBanners;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace KHHub.MasterDataService.Entities.HomeBanners;

public class HomeBanner : HomeBannerBase
{
    //<suite-custom-code-autogenerated>
    protected HomeBanner()
    {
    }

    public HomeBanner(Guid id, string title, string imageUrl, int sortOrder, bool isActive, string? subtitle = null, string? description = null, string? mobileImageUrl = null, string? buttonText = null, string? buttonUrl = null, TargetType? targetType = null, Guid? targetId = null, DateTime? startDate = null, DateTime? endDate = null) : base(id, title, imageUrl, sortOrder, isActive, subtitle, description, mobileImageUrl, buttonText, buttonUrl, targetType, targetId, startDate, endDate)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}