using KHHub.MasterDataService.Entities.HomeBanners;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Data.HomeBanners;

namespace KHHub.MasterDataService.Entities.HomeBanners;

public class HomeBannerManager : HomeBannerManagerBase
{
    //<suite-custom-code-autogenerated>
    public HomeBannerManager(IHomeBannerRepository homeBannerRepository) : base(homeBannerRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}