using KHHub.MasterDataService.Entities.Jobs;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace KHHub.MasterDataService.Entities.JobViews;

public class JobView : JobViewBase
{
    //<suite-custom-code-autogenerated>
    protected JobView()
    {
    }

    public JobView(Guid id, Guid jobId, DateTime viewedAt, int duration, Guid? userId = null, string? ipAddress = null, string? device = null, string? source = null) : base(id, jobId, viewedAt, duration, userId, ipAddress, device, source)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}