using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Data.JobViews;

namespace KHHub.MasterDataService.Entities.JobViews;

public class JobViewManager : JobViewManagerBase
{
    //<suite-custom-code-autogenerated>
    public JobViewManager(IJobViewRepository jobViewRepository) : base(jobViewRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}