using KHHub.MasterDataService.Services.Dtos.Shared;
using KHHub.MasterDataService.Entities.Places;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Permissions;
using KHHub.MasterDataService.Services.PlaceFavorites;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using KHHub.MasterDataService.Entities.PlaceFavorites;
using KHHub.MasterDataService.Services.Dtos.PlaceFavorites;
using KHHub.MasterDataService.Data.PlaceFavorites;
using KHHub.MasterDataService.Services.Dtos.Shared;

namespace KHHub.MasterDataService.Services.PlaceFavorites;

public class PlaceFavoritesAppService : PlaceFavoritesAppServiceBase, IPlaceFavoritesAppService
{
    //<suite-custom-code-autogenerated>
    public PlaceFavoritesAppService(IPlaceFavoriteRepository placeFavoriteRepository, PlaceFavoriteManager placeFavoriteManager, IDistributedCache<PlaceFavoriteDownloadTokenCacheItem, string> downloadTokenCache, IRepository<KHHub.MasterDataService.Entities.Places.Place, Guid> placeRepository) : base(placeFavoriteRepository, placeFavoriteManager, downloadTokenCache, placeRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}