using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Data.ArticleTags;

namespace KHHub.MasterDataService.Entities.ArticleTags;

public class ArticleTagManager : ArticleTagManagerBase
{
    //<suite-custom-code-autogenerated>
    public ArticleTagManager(IArticleTagRepository articleTagRepository) : base(articleTagRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}