using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace KHHub.MasterDataService.Entities.ArticleTags;

public class ArticleTag : ArticleTagBase
{
    //<suite-custom-code-autogenerated>
    protected ArticleTag()
    {
    }

    public ArticleTag(Guid id, string name, string slug, int usageCount, string? description = null) : base(id, name, slug, usageCount, description)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}