// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using KHHub.MasterDataService.Services.ArticleViews;
using KHHub.MasterDataService.Services.Dtos.ArticleViews;
using KHHub.MasterDataService.Services.Dtos.Shared;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Content;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace KHHub.MasterDataService.Services.ArticleViews;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IArticleViewsAppService), typeof(ArticleViewsClientProxy))]
public partial class ArticleViewsClientProxy : ClientProxyBase<IArticleViewsAppService>, IArticleViewsAppService
{
    public virtual async Task<PagedResultDto<ArticleViewWithNavigationPropertiesDto>> GetListAsync(GetArticleViewsInput input)
    {
        return await RequestAsync<PagedResultDto<ArticleViewWithNavigationPropertiesDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetArticleViewsInput), input }
        });
    }

    public virtual async Task<ArticleViewWithNavigationPropertiesDto> GetWithNavigationPropertiesAsync(Guid id)
    {
        return await RequestAsync<ArticleViewWithNavigationPropertiesDto>(nameof(GetWithNavigationPropertiesAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<ArticleViewDto> GetAsync(Guid id)
    {
        return await RequestAsync<ArticleViewDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PagedResultDto<LookupDto<Guid>>> GetArticleLookupAsync(LookupRequestDto input)
    {
        return await RequestAsync<PagedResultDto<LookupDto<Guid>>>(nameof(GetArticleLookupAsync), new ClientProxyRequestTypeValue
        {
            { typeof(LookupRequestDto), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<ArticleViewDto> CreateAsync(ArticleViewCreateDto input)
    {
        return await RequestAsync<ArticleViewDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ArticleViewCreateDto), input }
        });
    }

    public virtual async Task<ArticleViewDto> UpdateAsync(Guid id, ArticleViewUpdateDto input)
    {
        return await RequestAsync<ArticleViewDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(ArticleViewUpdateDto), input }
        });
    }

    public virtual async Task<IRemoteStreamContent> GetListAsExcelFileAsync(ArticleViewExcelDownloadDto input)
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(GetListAsExcelFileAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ArticleViewExcelDownloadDto), input }
        });
    }

    public virtual async Task DeleteByIdsAsync(List<Guid> articleviewIds)
    {
        await RequestAsync(nameof(DeleteByIdsAsync), new ClientProxyRequestTypeValue
        {
            { typeof(List<Guid>), articleviewIds }
        });
    }

    public virtual async Task DeleteAllAsync(GetArticleViewsInput input)
    {
        await RequestAsync(nameof(DeleteAllAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetArticleViewsInput), input }
        });
    }

    public virtual async Task<DownloadTokenResultDto> GetDownloadTokenAsync()
    {
        return await RequestAsync<DownloadTokenResultDto>(nameof(GetDownloadTokenAsync));
    }
}
