using KHHub.MasterDataService.Entities.Articles;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace KHHub.MasterDataService.Entities.ArticleViews;

public class ArticleView : ArticleViewBase
{
    //<suite-custom-code-autogenerated>
    protected ArticleView()
    {
    }

    public ArticleView(Guid id, Guid articleId, DateTime viewedAt, int duration, Guid userId, string? ipAddress = null, string? device = null, string? source = null) : base(id, articleId, viewedAt, duration, userId, ipAddress, device, source)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}