using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Data.ArticleViews;

namespace KHHub.MasterDataService.Entities.ArticleViews;

public class ArticleViewManager : ArticleViewManagerBase
{
    //<suite-custom-code-autogenerated>
    public ArticleViewManager(IArticleViewRepository articleViewRepository) : base(articleViewRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}