using KHHub.MasterDataService.Entities.Articles;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Data.Articles;

namespace KHHub.MasterDataService.Entities.Articles;

public class ArticleManager : ArticleManagerBase
{
    //<suite-custom-code-autogenerated>
    public ArticleManager(IArticleRepository articleRepository) : base(articleRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}