using KHHub.MasterDataService.Entities.Articles;
using KHHub.MasterDataService.Entities.ArticleCategories;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace KHHub.MasterDataService.Entities.Articles;

public class Article : ArticleBase
{
    //<suite-custom-code-autogenerated>
    protected Article()
    {
    }

    public Article(Guid id, Guid articleCategoryId, string title, string slug, string summary, string content, ArticleType type, string authorName, ArticleStatus status, DateTime publishedAt, bool isFeatured, bool isHot, bool isTrending, int viewCount, int likeCount, int shareCount, int commentCount, int readingTime, string seoTitle, string? thumbnailUrl = null, string? coverImageUrl = null, string? source = null, string? sourceUrl = null, string? seoDescription = null, string? seoKeywords = null) : base(id, articleCategoryId, title, slug, summary, content, type, authorName, status, publishedAt, isFeatured, isHot, isTrending, viewCount, likeCount, shareCount, commentCount, readingTime, seoTitle, thumbnailUrl, coverImageUrl, source, sourceUrl, seoDescription, seoKeywords)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}