// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using KHHub.CrawlerSerivce.Services;
using KHHub.CrawlerSerivce.Services.Dtos.Crawling;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace KHHub.CrawlerSerivce.Services;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IArticleNewsImportAppService), typeof(ArticleNewsImportClientProxy))]
public partial class ArticleNewsImportClientProxy : ClientProxyBase<IArticleNewsImportAppService>, IArticleNewsImportAppService
{
    public virtual async Task<ImportArticleListingResultDto> ImportFromListingAsync(ImportArticleListingInput input)
    {
        return await RequestAsync<ImportArticleListingResultDto>(nameof(ImportFromListingAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ImportArticleListingInput), input }
        });
    }
}
