// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using KHHub.CrawlerSerivce.Services;
using KHHub.CrawlerSerivce.Services.Dtos.Crawling;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace KHHub.CrawlerSerivce.Services;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IJobBoardImportAppService), typeof(JobBoardImportClientProxy))]
public partial class JobBoardImportClientProxy : ClientProxyBase<IJobBoardImportAppService>, IJobBoardImportAppService
{
    public virtual async Task<ImportJobListingResultDto> ImportFromListingAsync(ImportJobListingInput input)
    {
        return await RequestAsync<ImportJobListingResultDto>(nameof(ImportFromListingAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ImportJobListingInput), input }
        });
    }
}
