using KHHub.MasterDataService.Services.Dtos.Shared;
using KHHub.MasterDataService.Entities.Articles;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Permissions;
using KHHub.MasterDataService.Services.ArticleViews;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using KHHub.MasterDataService.Entities.ArticleViews;
using KHHub.MasterDataService.Services.Dtos.ArticleViews;
using KHHub.MasterDataService.Data.ArticleViews;
using KHHub.MasterDataService.Services.Dtos.Shared;

namespace KHHub.MasterDataService.Services.ArticleViews;

public class ArticleViewsAppService : ArticleViewsAppServiceBase, IArticleViewsAppService
{
    //<suite-custom-code-autogenerated>
    public ArticleViewsAppService(IArticleViewRepository articleViewRepository, ArticleViewManager articleViewManager, IDistributedCache<ArticleViewDownloadTokenCacheItem, string> downloadTokenCache, IRepository<KHHub.MasterDataService.Entities.Articles.Article, Guid> articleRepository) : base(articleViewRepository, articleViewManager, downloadTokenCache, articleRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}