using KHHub.MasterDataService.Services.Dtos.Shared;
using KHHub.MasterDataService.Entities.Places;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Permissions;
using KHHub.MasterDataService.Services.PlaceReviews;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using KHHub.MasterDataService.Entities.PlaceReviews;
using KHHub.MasterDataService.Services.Dtos.PlaceReviews;
using KHHub.MasterDataService.Data.PlaceReviews;
using KHHub.MasterDataService.Services.Dtos.Shared;

namespace KHHub.MasterDataService.Services.PlaceReviews;

public class PlaceReviewsAppService : PlaceReviewsAppServiceBase, IPlaceReviewsAppService
{
    //<suite-custom-code-autogenerated>
    public PlaceReviewsAppService(IPlaceReviewRepository placeReviewRepository, PlaceReviewManager placeReviewManager, IDistributedCache<PlaceReviewDownloadTokenCacheItem, string> downloadTokenCache, IRepository<KHHub.MasterDataService.Entities.Places.Place, Guid> placeRepository) : base(placeReviewRepository, placeReviewManager, downloadTokenCache, placeRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}