using KHHub.MasterDataService.Entities.Provinces;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace KHHub.MasterDataService.Entities.Wards;

public class Ward : WardBase
{
    //<suite-custom-code-autogenerated>
    protected Ward()
    {
    }

    public Ward(Guid id, Guid provinceId, string code, string name) : base(id, provinceId, code, name)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}