using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Data.Wards;

namespace KHHub.MasterDataService.Entities.Wards;

public class WardManager : WardManagerBase
{
    //<suite-custom-code-autogenerated>
    public WardManager(IWardRepository wardRepository) : base(wardRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}