using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Permissions;
using KHHub.MasterDataService.Services.ArticleCategories;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using KHHub.MasterDataService.Entities.ArticleCategories;
using KHHub.MasterDataService.Services.Dtos.ArticleCategories;
using KHHub.MasterDataService.Data.ArticleCategories;
using KHHub.MasterDataService.Services.Dtos.Shared;

namespace KHHub.MasterDataService.Services.ArticleCategories;

public class ArticleCategoriesAppService : ArticleCategoriesAppServiceBase, IArticleCategoriesAppService
{
    //<suite-custom-code-autogenerated>
    public ArticleCategoriesAppService(IArticleCategoryRepository articleCategoryRepository, ArticleCategoryManager articleCategoryManager, IDistributedCache<ArticleCategoryDownloadTokenCacheItem, string> downloadTokenCache) : base(articleCategoryRepository, articleCategoryManager, downloadTokenCache)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}