// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using KHHub.MasterDataService.Services.Dtos.PlaceViews;
using KHHub.MasterDataService.Services.Dtos.Shared;
using KHHub.MasterDataService.Services.PlaceViews;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Content;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace KHHub.MasterDataService.Services.PlaceViews;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IPlaceViewsAppService), typeof(PlaceViewsClientProxy))]
public partial class PlaceViewsClientProxy : ClientProxyBase<IPlaceViewsAppService>, IPlaceViewsAppService
{
    public virtual async Task<PagedResultDto<PlaceViewWithNavigationPropertiesDto>> GetListAsync(GetPlaceViewsInput input)
    {
        return await RequestAsync<PagedResultDto<PlaceViewWithNavigationPropertiesDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetPlaceViewsInput), input }
        });
    }

    public virtual async Task<PlaceViewWithNavigationPropertiesDto> GetWithNavigationPropertiesAsync(Guid id)
    {
        return await RequestAsync<PlaceViewWithNavigationPropertiesDto>(nameof(GetWithNavigationPropertiesAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PlaceViewDto> GetAsync(Guid id)
    {
        return await RequestAsync<PlaceViewDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PagedResultDto<LookupDto<Guid>>> GetPlaceLookupAsync(LookupRequestDto input)
    {
        return await RequestAsync<PagedResultDto<LookupDto<Guid>>>(nameof(GetPlaceLookupAsync), new ClientProxyRequestTypeValue
        {
            { typeof(LookupRequestDto), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PlaceViewDto> CreateAsync(PlaceViewCreateDto input)
    {
        return await RequestAsync<PlaceViewDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PlaceViewCreateDto), input }
        });
    }

    public virtual async Task<PlaceViewDto> UpdateAsync(Guid id, PlaceViewUpdateDto input)
    {
        return await RequestAsync<PlaceViewDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(PlaceViewUpdateDto), input }
        });
    }

    public virtual async Task<IRemoteStreamContent> GetListAsExcelFileAsync(PlaceViewExcelDownloadDto input)
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(GetListAsExcelFileAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PlaceViewExcelDownloadDto), input }
        });
    }

    public virtual async Task DeleteByIdsAsync(List<Guid> placeviewIds)
    {
        await RequestAsync(nameof(DeleteByIdsAsync), new ClientProxyRequestTypeValue
        {
            { typeof(List<Guid>), placeviewIds }
        });
    }

    public virtual async Task DeleteAllAsync(GetPlaceViewsInput input)
    {
        await RequestAsync(nameof(DeleteAllAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetPlaceViewsInput), input }
        });
    }

    public virtual async Task<DownloadTokenResultDto> GetDownloadTokenAsync()
    {
        return await RequestAsync<DownloadTokenResultDto>(nameof(GetDownloadTokenAsync));
    }
}
