// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using KHHub.MasterDataService.Services.Dtos.PlaceCategories;
using KHHub.MasterDataService.Services.Dtos.Shared;
using KHHub.MasterDataService.Services.PlaceCategories;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Content;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace KHHub.MasterDataService.Services.PlaceCategories;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IPlaceCategoriesAppService), typeof(PlaceCategoriesClientProxy))]
public partial class PlaceCategoriesClientProxy : ClientProxyBase<IPlaceCategoriesAppService>, IPlaceCategoriesAppService
{
    public virtual async Task<PagedResultDto<PlaceCategoryDto>> GetListAsync(GetPlaceCategoriesInput input)
    {
        return await RequestAsync<PagedResultDto<PlaceCategoryDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetPlaceCategoriesInput), input }
        });
    }

    public virtual async Task<PlaceCategoryDto> GetAsync(Guid id)
    {
        return await RequestAsync<PlaceCategoryDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PlaceCategoryDto> CreateAsync(PlaceCategoryCreateDto input)
    {
        return await RequestAsync<PlaceCategoryDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PlaceCategoryCreateDto), input }
        });
    }

    public virtual async Task<PlaceCategoryDto> UpdateAsync(Guid id, PlaceCategoryUpdateDto input)
    {
        return await RequestAsync<PlaceCategoryDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(PlaceCategoryUpdateDto), input }
        });
    }

    public virtual async Task<IRemoteStreamContent> GetListAsExcelFileAsync(PlaceCategoryExcelDownloadDto input)
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(GetListAsExcelFileAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PlaceCategoryExcelDownloadDto), input }
        });
    }

    public virtual async Task DeleteByIdsAsync(List<Guid> placecategoryIds)
    {
        await RequestAsync(nameof(DeleteByIdsAsync), new ClientProxyRequestTypeValue
        {
            { typeof(List<Guid>), placecategoryIds }
        });
    }

    public virtual async Task DeleteAllAsync(GetPlaceCategoriesInput input)
    {
        await RequestAsync(nameof(DeleteAllAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetPlaceCategoriesInput), input }
        });
    }

    public virtual async Task<DownloadTokenResultDto> GetDownloadTokenAsync()
    {
        return await RequestAsync<DownloadTokenResultDto>(nameof(GetDownloadTokenAsync));
    }
}
