// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using KHHub.MasterDataService.Services.ArticleCategories;
using KHHub.MasterDataService.Services.Dtos.ArticleCategories;
using KHHub.MasterDataService.Services.Dtos.Shared;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Content;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace KHHub.MasterDataService.Services.ArticleCategories;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IArticleCategoriesAppService), typeof(ArticleCategoriesClientProxy))]
public partial class ArticleCategoriesClientProxy : ClientProxyBase<IArticleCategoriesAppService>, IArticleCategoriesAppService
{
    public virtual async Task<PagedResultDto<ArticleCategoryDto>> GetListAsync(GetArticleCategoriesInput input)
    {
        return await RequestAsync<PagedResultDto<ArticleCategoryDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetArticleCategoriesInput), input }
        });
    }

    public virtual async Task<ArticleCategoryDto> GetAsync(Guid id)
    {
        return await RequestAsync<ArticleCategoryDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<ArticleCategoryDto> CreateAsync(ArticleCategoryCreateDto input)
    {
        return await RequestAsync<ArticleCategoryDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ArticleCategoryCreateDto), input }
        });
    }

    public virtual async Task<ArticleCategoryDto> UpdateAsync(Guid id, ArticleCategoryUpdateDto input)
    {
        return await RequestAsync<ArticleCategoryDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(ArticleCategoryUpdateDto), input }
        });
    }

    public virtual async Task<IRemoteStreamContent> GetListAsExcelFileAsync(ArticleCategoryExcelDownloadDto input)
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(GetListAsExcelFileAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ArticleCategoryExcelDownloadDto), input }
        });
    }

    public virtual async Task DeleteByIdsAsync(List<Guid> articlecategoryIds)
    {
        await RequestAsync(nameof(DeleteByIdsAsync), new ClientProxyRequestTypeValue
        {
            { typeof(List<Guid>), articlecategoryIds }
        });
    }

    public virtual async Task DeleteAllAsync(GetArticleCategoriesInput input)
    {
        await RequestAsync(nameof(DeleteAllAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetArticleCategoriesInput), input }
        });
    }

    public virtual async Task<DownloadTokenResultDto> GetDownloadTokenAsync()
    {
        return await RequestAsync<DownloadTokenResultDto>(nameof(GetDownloadTokenAsync));
    }
}
