using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Data.EntityFiles;

namespace KHHub.MasterDataService.Entities.EntityFiles;

public class EntityFileManager : EntityFileManagerBase
{
    //<suite-custom-code-autogenerated>
    public EntityFileManager(IEntityFileRepository entityFileRepository) : base(entityFileRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}