using KHHub.MasterDataService.Entities.MediaFiles;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace KHHub.MasterDataService.Entities.EntityFiles;

public class EntityFile : EntityFileBase
{
    //<suite-custom-code-autogenerated>
    protected EntityFile()
    {
    }

    public EntityFile(Guid id, Guid mediaFileId, string entityType, Guid entityId, int sortOrder, bool isPrimary, string? collection = null) : base(id, mediaFileId, entityType, entityId, sortOrder, isPrimary, collection)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}