using KHHub.MasterDataService.Services.Dtos.Shared;
using KHHub.MasterDataService.Entities.Places;
using KHHub.MasterDataService.Entities.PlaceTags;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Permissions;
using KHHub.MasterDataService.Services.PlaceTagMappings;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using KHHub.MasterDataService.Entities.PlaceTagMappings;
using KHHub.MasterDataService.Services.Dtos.PlaceTagMappings;
using KHHub.MasterDataService.Data.PlaceTagMappings;
using KHHub.MasterDataService.Services.Dtos.Shared;

namespace KHHub.MasterDataService.Services.PlaceTagMappings;

public class PlaceTagMappingsAppService : PlaceTagMappingsAppServiceBase, IPlaceTagMappingsAppService
{
    //<suite-custom-code-autogenerated>
    public PlaceTagMappingsAppService(IPlaceTagMappingRepository placeTagMappingRepository, PlaceTagMappingManager placeTagMappingManager, IDistributedCache<PlaceTagMappingDownloadTokenCacheItem, string> downloadTokenCache, IRepository<KHHub.MasterDataService.Entities.PlaceTags.PlaceTag, Guid> placeTagRepository, IRepository<KHHub.MasterDataService.Entities.Places.Place, Guid> placeRepository) : base(placeTagMappingRepository, placeTagMappingManager, downloadTokenCache, placeTagRepository, placeRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}