using KHHub.MasterDataService.Entities.MediaFiles;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace KHHub.MasterDataService.Entities.MediaFiles;

public class MediaFile : MediaFileBase
{
    //<suite-custom-code-autogenerated>
    protected MediaFile()
    {
    }

    public MediaFile(Guid id, long size, int width, int height, int duration, FileType fileType, FileStatus status, string? fileName = null, string? originalFileName = null, string? extension = null, string? contentType = null, string? storageProvider = null, string? bucket = null, string? folder = null, string? path = null, string? url = null, string? checksum = null) : base(id, size, width, height, duration, fileType, status, fileName, originalFileName, extension, contentType, storageProvider, bucket, folder, path, url, checksum)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}