using KHHub.MasterDataService.Entities.MediaFiles;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Data.MediaFiles;

namespace KHHub.MasterDataService.Entities.MediaFiles;

public class MediaFileManager : MediaFileManagerBase
{
    //<suite-custom-code-autogenerated>
    public MediaFileManager(IMediaFileRepository mediaFileRepository) : base(mediaFileRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}