// This file is automatically generated by ABP Suite.
namespace KHHub.MasterDataService.Entities.PlaceReviews;

public enum PlaceReviewStatus
{
    Pending = 0,
    Approved = 1,
    Rejected = 2
}