using KHHub.MasterDataService.Services.Dtos.Shared;
using KHHub.MasterDataService.Entities.Jobs;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Permissions;
using KHHub.MasterDataService.Services.JobViews;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using KHHub.MasterDataService.Entities.JobViews;
using KHHub.MasterDataService.Services.Dtos.JobViews;
using KHHub.MasterDataService.Data.JobViews;
using KHHub.MasterDataService.Services.Dtos.Shared;

namespace KHHub.MasterDataService.Services.JobViews;

public class JobViewsAppService : JobViewsAppServiceBase, IJobViewsAppService
{
    //<suite-custom-code-autogenerated>
    public JobViewsAppService(IJobViewRepository jobViewRepository, JobViewManager jobViewManager, IDistributedCache<JobViewDownloadTokenCacheItem, string> downloadTokenCache, IRepository<KHHub.MasterDataService.Entities.Jobs.Job, Guid> jobRepository) : base(jobViewRepository, jobViewManager, downloadTokenCache, jobRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}