using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Permissions;
using KHHub.MasterDataService.Services.Provinces;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using KHHub.MasterDataService.Entities.Provinces;
using KHHub.MasterDataService.Services.Dtos.Provinces;
using KHHub.MasterDataService.Data.Provinces;
using KHHub.MasterDataService.Services.Dtos.Shared;

namespace KHHub.MasterDataService.Services.Provinces;

public class ProvincesAppService : ProvincesAppServiceBase, IProvincesAppService
{
    //<suite-custom-code-autogenerated>
    public ProvincesAppService(IProvinceRepository provinceRepository, ProvinceManager provinceManager, IDistributedCache<ProvinceDownloadTokenCacheItem, string> downloadTokenCache) : base(provinceRepository, provinceManager, downloadTokenCache)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}