// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using KHHub.MasterDataService.Services.Dtos.JobTagMappings;
using KHHub.MasterDataService.Services.Dtos.Shared;
using KHHub.MasterDataService.Services.JobTagMappings;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Content;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace KHHub.MasterDataService.Services.JobTagMappings;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IJobTagMappingsAppService), typeof(JobTagMappingsClientProxy))]
public partial class JobTagMappingsClientProxy : ClientProxyBase<IJobTagMappingsAppService>, IJobTagMappingsAppService
{
    public virtual async Task<PagedResultDto<JobTagMappingWithNavigationPropertiesDto>> GetListAsync(GetJobTagMappingsInput input)
    {
        return await RequestAsync<PagedResultDto<JobTagMappingWithNavigationPropertiesDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetJobTagMappingsInput), input }
        });
    }

    public virtual async Task<JobTagMappingWithNavigationPropertiesDto> GetWithNavigationPropertiesAsync(Guid id)
    {
        return await RequestAsync<JobTagMappingWithNavigationPropertiesDto>(nameof(GetWithNavigationPropertiesAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<JobTagMappingDto> GetAsync(Guid id)
    {
        return await RequestAsync<JobTagMappingDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PagedResultDto<LookupDto<Guid>>> GetJobTagLookupAsync(LookupRequestDto input)
    {
        return await RequestAsync<PagedResultDto<LookupDto<Guid>>>(nameof(GetJobTagLookupAsync), new ClientProxyRequestTypeValue
        {
            { typeof(LookupRequestDto), input }
        });
    }

    public virtual async Task<PagedResultDto<LookupDto<Guid>>> GetJobLookupAsync(LookupRequestDto input)
    {
        return await RequestAsync<PagedResultDto<LookupDto<Guid>>>(nameof(GetJobLookupAsync), new ClientProxyRequestTypeValue
        {
            { typeof(LookupRequestDto), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<JobTagMappingDto> CreateAsync(JobTagMappingCreateDto input)
    {
        return await RequestAsync<JobTagMappingDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(JobTagMappingCreateDto), input }
        });
    }

    public virtual async Task<JobTagMappingDto> UpdateAsync(Guid id, JobTagMappingUpdateDto input)
    {
        return await RequestAsync<JobTagMappingDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(JobTagMappingUpdateDto), input }
        });
    }

    public virtual async Task<IRemoteStreamContent> GetListAsExcelFileAsync(JobTagMappingExcelDownloadDto input)
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(GetListAsExcelFileAsync), new ClientProxyRequestTypeValue
        {
            { typeof(JobTagMappingExcelDownloadDto), input }
        });
    }

    public virtual async Task DeleteByIdsAsync(List<Guid> jobtagmappingIds)
    {
        await RequestAsync(nameof(DeleteByIdsAsync), new ClientProxyRequestTypeValue
        {
            { typeof(List<Guid>), jobtagmappingIds }
        });
    }

    public virtual async Task DeleteAllAsync(GetJobTagMappingsInput input)
    {
        await RequestAsync(nameof(DeleteAllAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetJobTagMappingsInput), input }
        });
    }

    public virtual async Task<DownloadTokenResultDto> GetDownloadTokenAsync()
    {
        return await RequestAsync<DownloadTokenResultDto>(nameof(GetDownloadTokenAsync));
    }
}
