using KHHub.MasterDataService.Services.Dtos.Shared;
using KHHub.MasterDataService.Entities.Jobs;
using KHHub.MasterDataService.Entities.JobTags;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Permissions;
using KHHub.MasterDataService.Services.JobTagMappings;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using KHHub.MasterDataService.Entities.JobTagMappings;
using KHHub.MasterDataService.Services.Dtos.JobTagMappings;
using KHHub.MasterDataService.Data.JobTagMappings;
using KHHub.MasterDataService.Services.Dtos.Shared;

namespace KHHub.MasterDataService.Services.JobTagMappings;

public class JobTagMappingsAppService : JobTagMappingsAppServiceBase, IJobTagMappingsAppService
{
    //<suite-custom-code-autogenerated>
    public JobTagMappingsAppService(IJobTagMappingRepository jobTagMappingRepository, JobTagMappingManager jobTagMappingManager, IDistributedCache<JobTagMappingDownloadTokenCacheItem, string> downloadTokenCache, IRepository<KHHub.MasterDataService.Entities.JobTags.JobTag, Guid> jobTagRepository, IRepository<KHHub.MasterDataService.Entities.Jobs.Job, Guid> jobRepository) : base(jobTagMappingRepository, jobTagMappingManager, downloadTokenCache, jobTagRepository, jobRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}