// This file is automatically generated by ABP Suite.
namespace KHHub.MasterDataService.Entities.HomeBanners;

public enum TargetType
{
    Article = 0,
    Place = 1,
    Event = 2,
    ExternalUrl = 3
}