using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Data.PlaceViews;

namespace KHHub.MasterDataService.Entities.PlaceViews;

public class PlaceViewManager : PlaceViewManagerBase
{
    //<suite-custom-code-autogenerated>
    public PlaceViewManager(IPlaceViewRepository placeViewRepository) : base(placeViewRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}