using KHHub.MasterDataService.Entities.Places;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace KHHub.MasterDataService.Entities.PlaceViews;

public class PlaceView : PlaceViewBase
{
    //<suite-custom-code-autogenerated>
    protected PlaceView()
    {
    }

    public PlaceView(Guid id, Guid placeId, Guid userId, DateTime viewedAt, int duration, string? ipAddress = null, string? device = null, string? source = null) : base(id, placeId, userId, viewedAt, duration, ipAddress, device, source)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}