using KHHub.MasterDataService.Entities.PlaceTags;
using KHHub.MasterDataService.Entities.Places;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace KHHub.MasterDataService.Entities.PlaceTagMappings;

public class PlaceTagMapping : PlaceTagMappingBase
{
    //<suite-custom-code-autogenerated>
    protected PlaceTagMapping()
    {
    }

    public PlaceTagMapping(Guid id, Guid placeTagId, Guid placeId, bool isPrimary, int sortOrder) : base(id, placeTagId, placeId, isPrimary, sortOrder)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}