using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Data.PlaceTagMappings;

namespace KHHub.MasterDataService.Entities.PlaceTagMappings;

public class PlaceTagMappingManager : PlaceTagMappingManagerBase
{
    //<suite-custom-code-autogenerated>
    public PlaceTagMappingManager(IPlaceTagMappingRepository placeTagMappingRepository) : base(placeTagMappingRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}