// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using KHHub.MasterDataService.Services.Dtos.Provinces;
using KHHub.MasterDataService.Services.Dtos.Shared;
using KHHub.MasterDataService.Services.Provinces;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Content;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace KHHub.MasterDataService.Services.Provinces;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IProvincesAppService), typeof(ProvincesClientProxy))]
public partial class ProvincesClientProxy : ClientProxyBase<IProvincesAppService>, IProvincesAppService
{
    public virtual async Task<PagedResultDto<ProvinceDto>> GetListAsync(GetProvincesInput input)
    {
        return await RequestAsync<PagedResultDto<ProvinceDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetProvincesInput), input }
        });
    }

    public virtual async Task<ProvinceDto> GetAsync(Guid id)
    {
        return await RequestAsync<ProvinceDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<ProvinceDto> CreateAsync(ProvinceCreateDto input)
    {
        return await RequestAsync<ProvinceDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ProvinceCreateDto), input }
        });
    }

    public virtual async Task<ProvinceDto> UpdateAsync(Guid id, ProvinceUpdateDto input)
    {
        return await RequestAsync<ProvinceDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(ProvinceUpdateDto), input }
        });
    }

    public virtual async Task<IRemoteStreamContent> GetListAsExcelFileAsync(ProvinceExcelDownloadDto input)
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(GetListAsExcelFileAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ProvinceExcelDownloadDto), input }
        });
    }

    public virtual async Task DeleteByIdsAsync(List<Guid> provinceIds)
    {
        await RequestAsync(nameof(DeleteByIdsAsync), new ClientProxyRequestTypeValue
        {
            { typeof(List<Guid>), provinceIds }
        });
    }

    public virtual async Task DeleteAllAsync(GetProvincesInput input)
    {
        await RequestAsync(nameof(DeleteAllAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetProvincesInput), input }
        });
    }

    public virtual async Task<DownloadTokenResultDto> GetDownloadTokenAsync()
    {
        return await RequestAsync<DownloadTokenResultDto>(nameof(GetDownloadTokenAsync));
    }
}
