using KHHub.MasterDataService.Entities.PlaceReviews;
using KHHub.MasterDataService.Entities.Places;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace KHHub.MasterDataService.Entities.PlaceReviews;

public class PlaceReview : PlaceReviewBase
{
    //<suite-custom-code-autogenerated>
    protected PlaceReview()
    {
    }

    public PlaceReview(Guid id, Guid placeId, int rating, string title, int likeCount, PlaceReviewStatus status, string? comment = null, Guid? userId = null) : base(id, placeId, rating, title, likeCount, status, comment, userId)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}