using KHHub.MasterDataService.Entities.PlaceReviews;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Data.PlaceReviews;

namespace KHHub.MasterDataService.Entities.PlaceReviews;

public class PlaceReviewManager : PlaceReviewManagerBase
{
    //<suite-custom-code-autogenerated>
    public PlaceReviewManager(IPlaceReviewRepository placeReviewRepository) : base(placeReviewRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}