using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Data.JobFavorites;

namespace KHHub.MasterDataService.Entities.JobFavorites;

public class JobFavoriteManager : JobFavoriteManagerBase
{
    //<suite-custom-code-autogenerated>
    public JobFavoriteManager(IJobFavoriteRepository jobFavoriteRepository) : base(jobFavoriteRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}