using KHHub.MasterDataService.Entities.Jobs;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace KHHub.MasterDataService.Entities.JobFavorites;

public class JobFavorite : JobFavoriteBase
{
    //<suite-custom-code-autogenerated>
    protected JobFavorite()
    {
    }

    public JobFavorite(Guid id, Guid jobId, Guid userId) : base(id, jobId, userId)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}