using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Data.JobTags;

namespace KHHub.MasterDataService.Entities.JobTags;

public class JobTagManager : JobTagManagerBase
{
    //<suite-custom-code-autogenerated>
    public JobTagManager(IJobTagRepository jobTagRepository) : base(jobTagRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}