// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using KHHub.MasterDataService.Services.Dtos.EntityFiles;
using KHHub.MasterDataService.Services.Dtos.Shared;
using KHHub.MasterDataService.Services.EntityFiles;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Content;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace KHHub.MasterDataService.Services.EntityFiles;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IEntityFilesAppService), typeof(EntityFilesClientProxy))]
public partial class EntityFilesClientProxy : ClientProxyBase<IEntityFilesAppService>, IEntityFilesAppService
{
    public virtual async Task<PagedResultDto<EntityFileWithNavigationPropertiesDto>> GetListAsync(GetEntityFilesInput input)
    {
        return await RequestAsync<PagedResultDto<EntityFileWithNavigationPropertiesDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetEntityFilesInput), input }
        });
    }

    public virtual async Task<EntityFileWithNavigationPropertiesDto> GetWithNavigationPropertiesAsync(Guid id)
    {
        return await RequestAsync<EntityFileWithNavigationPropertiesDto>(nameof(GetWithNavigationPropertiesAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<EntityFileDto> GetAsync(Guid id)
    {
        return await RequestAsync<EntityFileDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PagedResultDto<LookupDto<Guid>>> GetMediaFileLookupAsync(LookupRequestDto input)
    {
        return await RequestAsync<PagedResultDto<LookupDto<Guid>>>(nameof(GetMediaFileLookupAsync), new ClientProxyRequestTypeValue
        {
            { typeof(LookupRequestDto), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<EntityFileDto> CreateAsync(EntityFileCreateDto input)
    {
        return await RequestAsync<EntityFileDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(EntityFileCreateDto), input }
        });
    }

    public virtual async Task<EntityFileDto> UpdateAsync(Guid id, EntityFileUpdateDto input)
    {
        return await RequestAsync<EntityFileDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(EntityFileUpdateDto), input }
        });
    }

    public virtual async Task<IRemoteStreamContent> GetListAsExcelFileAsync(EntityFileExcelDownloadDto input)
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(GetListAsExcelFileAsync), new ClientProxyRequestTypeValue
        {
            { typeof(EntityFileExcelDownloadDto), input }
        });
    }

    public virtual async Task DeleteByIdsAsync(List<Guid> entityfileIds)
    {
        await RequestAsync(nameof(DeleteByIdsAsync), new ClientProxyRequestTypeValue
        {
            { typeof(List<Guid>), entityfileIds }
        });
    }

    public virtual async Task DeleteAllAsync(GetEntityFilesInput input)
    {
        await RequestAsync(nameof(DeleteAllAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetEntityFilesInput), input }
        });
    }

    public virtual async Task<DownloadTokenResultDto> GetDownloadTokenAsync()
    {
        return await RequestAsync<DownloadTokenResultDto>(nameof(GetDownloadTokenAsync));
    }
}
