// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using KHHub.MasterDataService.Services.Dtos.PlaceReviews;
using KHHub.MasterDataService.Services.Dtos.Shared;
using KHHub.MasterDataService.Services.PlaceReviews;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Content;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace KHHub.MasterDataService.Services.PlaceReviews;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IPlaceReviewsAppService), typeof(PlaceReviewsClientProxy))]
public partial class PlaceReviewsClientProxy : ClientProxyBase<IPlaceReviewsAppService>, IPlaceReviewsAppService
{
    public virtual async Task<PagedResultDto<PlaceReviewWithNavigationPropertiesDto>> GetListAsync(GetPlaceReviewsInput input)
    {
        return await RequestAsync<PagedResultDto<PlaceReviewWithNavigationPropertiesDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetPlaceReviewsInput), input }
        });
    }

    public virtual async Task<PlaceReviewWithNavigationPropertiesDto> GetWithNavigationPropertiesAsync(Guid id)
    {
        return await RequestAsync<PlaceReviewWithNavigationPropertiesDto>(nameof(GetWithNavigationPropertiesAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PlaceReviewDto> GetAsync(Guid id)
    {
        return await RequestAsync<PlaceReviewDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PagedResultDto<LookupDto<Guid>>> GetPlaceLookupAsync(LookupRequestDto input)
    {
        return await RequestAsync<PagedResultDto<LookupDto<Guid>>>(nameof(GetPlaceLookupAsync), new ClientProxyRequestTypeValue
        {
            { typeof(LookupRequestDto), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PlaceReviewDto> CreateAsync(PlaceReviewCreateDto input)
    {
        return await RequestAsync<PlaceReviewDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PlaceReviewCreateDto), input }
        });
    }

    public virtual async Task<PlaceReviewDto> UpdateAsync(Guid id, PlaceReviewUpdateDto input)
    {
        return await RequestAsync<PlaceReviewDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(PlaceReviewUpdateDto), input }
        });
    }

    public virtual async Task<IRemoteStreamContent> GetListAsExcelFileAsync(PlaceReviewExcelDownloadDto input)
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(GetListAsExcelFileAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PlaceReviewExcelDownloadDto), input }
        });
    }

    public virtual async Task DeleteByIdsAsync(List<Guid> placereviewIds)
    {
        await RequestAsync(nameof(DeleteByIdsAsync), new ClientProxyRequestTypeValue
        {
            { typeof(List<Guid>), placereviewIds }
        });
    }

    public virtual async Task DeleteAllAsync(GetPlaceReviewsInput input)
    {
        await RequestAsync(nameof(DeleteAllAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetPlaceReviewsInput), input }
        });
    }

    public virtual async Task<DownloadTokenResultDto> GetDownloadTokenAsync()
    {
        return await RequestAsync<DownloadTokenResultDto>(nameof(GetDownloadTokenAsync));
    }
}
