using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Permissions;
using KHHub.MasterDataService.Services.HomeBanners;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using KHHub.MasterDataService.Entities.HomeBanners;
using KHHub.MasterDataService.Services.Dtos.HomeBanners;
using KHHub.MasterDataService.Data.HomeBanners;
using KHHub.MasterDataService.Services.Dtos.Shared;

namespace KHHub.MasterDataService.Services.HomeBanners;

public class HomeBannersAppService : HomeBannersAppServiceBase, IHomeBannersAppService
{
    //<suite-custom-code-autogenerated>
    public HomeBannersAppService(IHomeBannerRepository homeBannerRepository, HomeBannerManager homeBannerManager, IDistributedCache<HomeBannerDownloadTokenCacheItem, string> downloadTokenCache) : base(homeBannerRepository, homeBannerManager, downloadTokenCache)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}