// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using KHHub.MasterDataService.Services.Dtos.JobCategories;
using KHHub.MasterDataService.Services.Dtos.Shared;
using KHHub.MasterDataService.Services.JobCategories;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Content;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace KHHub.MasterDataService.Services.JobCategories;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IJobCategoriesAppService), typeof(JobCategoriesClientProxy))]
public partial class JobCategoriesClientProxy : ClientProxyBase<IJobCategoriesAppService>, IJobCategoriesAppService
{
    public virtual async Task<PagedResultDto<JobCategoryDto>> GetListAsync(GetJobCategoriesInput input)
    {
        return await RequestAsync<PagedResultDto<JobCategoryDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetJobCategoriesInput), input }
        });
    }

    public virtual async Task<JobCategoryDto> GetAsync(Guid id)
    {
        return await RequestAsync<JobCategoryDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<JobCategoryDto> CreateAsync(JobCategoryCreateDto input)
    {
        return await RequestAsync<JobCategoryDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(JobCategoryCreateDto), input }
        });
    }

    public virtual async Task<JobCategoryDto> UpdateAsync(Guid id, JobCategoryUpdateDto input)
    {
        return await RequestAsync<JobCategoryDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(JobCategoryUpdateDto), input }
        });
    }

    public virtual async Task<IRemoteStreamContent> GetListAsExcelFileAsync(JobCategoryExcelDownloadDto input)
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(GetListAsExcelFileAsync), new ClientProxyRequestTypeValue
        {
            { typeof(JobCategoryExcelDownloadDto), input }
        });
    }

    public virtual async Task DeleteByIdsAsync(List<Guid> jobcategoryIds)
    {
        await RequestAsync(nameof(DeleteByIdsAsync), new ClientProxyRequestTypeValue
        {
            { typeof(List<Guid>), jobcategoryIds }
        });
    }

    public virtual async Task DeleteAllAsync(GetJobCategoriesInput input)
    {
        await RequestAsync(nameof(DeleteAllAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetJobCategoriesInput), input }
        });
    }

    public virtual async Task<DownloadTokenResultDto> GetDownloadTokenAsync()
    {
        return await RequestAsync<DownloadTokenResultDto>(nameof(GetDownloadTokenAsync));
    }
}
