using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Data.PlaceTags;

namespace KHHub.MasterDataService.Entities.PlaceTags;

public class PlaceTagManager : PlaceTagManagerBase
{
    //<suite-custom-code-autogenerated>
    public PlaceTagManager(IPlaceTagRepository placeTagRepository) : base(placeTagRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}