// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using KHHub.MasterDataService.Services.ArticleTags;
using KHHub.MasterDataService.Services.Dtos.ArticleTags;
using KHHub.MasterDataService.Services.Dtos.Shared;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Content;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace KHHub.MasterDataService.Services.ArticleTags;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IArticleTagsAppService), typeof(ArticleTagsClientProxy))]
public partial class ArticleTagsClientProxy : ClientProxyBase<IArticleTagsAppService>, IArticleTagsAppService
{
    public virtual async Task<PagedResultDto<ArticleTagDto>> GetListAsync(GetArticleTagsInput input)
    {
        return await RequestAsync<PagedResultDto<ArticleTagDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetArticleTagsInput), input }
        });
    }

    public virtual async Task<ArticleTagDto> GetAsync(Guid id)
    {
        return await RequestAsync<ArticleTagDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<ArticleTagDto> CreateAsync(ArticleTagCreateDto input)
    {
        return await RequestAsync<ArticleTagDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ArticleTagCreateDto), input }
        });
    }

    public virtual async Task<ArticleTagDto> UpdateAsync(Guid id, ArticleTagUpdateDto input)
    {
        return await RequestAsync<ArticleTagDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(ArticleTagUpdateDto), input }
        });
    }

    public virtual async Task<IRemoteStreamContent> GetListAsExcelFileAsync(ArticleTagExcelDownloadDto input)
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(GetListAsExcelFileAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ArticleTagExcelDownloadDto), input }
        });
    }

    public virtual async Task DeleteByIdsAsync(List<Guid> articletagIds)
    {
        await RequestAsync(nameof(DeleteByIdsAsync), new ClientProxyRequestTypeValue
        {
            { typeof(List<Guid>), articletagIds }
        });
    }

    public virtual async Task DeleteAllAsync(GetArticleTagsInput input)
    {
        await RequestAsync(nameof(DeleteAllAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetArticleTagsInput), input }
        });
    }

    public virtual async Task<DownloadTokenResultDto> GetDownloadTokenAsync()
    {
        return await RequestAsync<DownloadTokenResultDto>(nameof(GetDownloadTokenAsync));
    }
}
