using KHHub.MasterDataService.Services.Dtos.Shared;
using KHHub.MasterDataService.Data.JobCategories;
using KHHub.MasterDataService.Services.Dtos.JobCategories;
using KHHub.MasterDataService.Entities.JobCategories;
using KHHub.MasterDataService.Services.Dtos.Shared;
using KHHub.MasterDataService.Data.JobCategories;
using KHHub.MasterDataService.Services.Dtos.JobCategories;
using KHHub.MasterDataService.Entities.JobCategories;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Permissions;
using KHHub.MasterDataService.Services.JobCategories;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using KHHub.MasterDataService.Entities.JobCategories;
using KHHub.MasterDataService.Services.Dtos.JobCategories;
using KHHub.MasterDataService.Data.JobCategories;
using KHHub.MasterDataService.Services.Dtos.Shared;

namespace KHHub.MasterDataService.Services.JobCategories;

public class JobCategoriesAppService : JobCategoriesAppServiceBase, IJobCategoriesAppService
{
    //<suite-custom-code-autogenerated>
    public JobCategoriesAppService(IJobCategoryRepository jobCategoryRepository, JobCategoryManager jobCategoryManager, IDistributedCache<JobCategoryDownloadTokenCacheItem, string> downloadTokenCache) : base(jobCategoryRepository, jobCategoryManager, downloadTokenCache)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}