using KHHub.MasterDataService.Services.Dtos.Shared;
using KHHub.MasterDataService.Entities.JobCategories;
using KHHub.MasterDataService.Entities.Wards;
using KHHub.MasterDataService.Entities.Provinces;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Permissions;
using KHHub.MasterDataService.Services.Jobs;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using KHHub.MasterDataService.Entities.Jobs;
using KHHub.MasterDataService.Services.Dtos.Jobs;
using KHHub.MasterDataService.Data.Jobs;
using KHHub.MasterDataService.Services.Dtos.Shared;

namespace KHHub.MasterDataService.Services.Jobs;

public class JobsAppService : JobsAppServiceBase, IJobsAppService
{
    //<suite-custom-code-autogenerated>
    public JobsAppService(IJobRepository jobRepository, JobManager jobManager, IDistributedCache<JobDownloadTokenCacheItem, string> downloadTokenCache, IRepository<KHHub.MasterDataService.Entities.Provinces.Province, Guid> provinceRepository, IRepository<KHHub.MasterDataService.Entities.Wards.Ward, Guid> wardRepository, IRepository<KHHub.MasterDataService.Entities.JobCategories.JobCategory, Guid> jobCategoryRepository) : base(jobRepository, jobManager, downloadTokenCache, provinceRepository, wardRepository, jobCategoryRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}