// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using KHHub.MasterDataService.Services.Dtos.Places;
using KHHub.MasterDataService.Services.Dtos.Shared;
using KHHub.MasterDataService.Services.Places;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Content;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace KHHub.MasterDataService.Services.Places;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IPlacesAppService), typeof(PlacesClientProxy))]
public partial class PlacesClientProxy : ClientProxyBase<IPlacesAppService>, IPlacesAppService
{
    public virtual async Task<PagedResultDto<PlaceWithNavigationPropertiesDto>> GetListAsync(GetPlacesInput input)
    {
        return await RequestAsync<PagedResultDto<PlaceWithNavigationPropertiesDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetPlacesInput), input }
        });
    }

    public virtual async Task<PlaceWithNavigationPropertiesDto> GetWithNavigationPropertiesAsync(Guid id)
    {
        return await RequestAsync<PlaceWithNavigationPropertiesDto>(nameof(GetWithNavigationPropertiesAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PlaceDto> GetAsync(Guid id)
    {
        return await RequestAsync<PlaceDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PagedResultDto<LookupDto<Guid>>> GetPlaceCategoryLookupAsync(LookupRequestDto input)
    {
        return await RequestAsync<PagedResultDto<LookupDto<Guid>>>(nameof(GetPlaceCategoryLookupAsync), new ClientProxyRequestTypeValue
        {
            { typeof(LookupRequestDto), input }
        });
    }

    public virtual async Task<PagedResultDto<LookupDto<Guid>>> GetProvinceLookupAsync(LookupRequestDto input)
    {
        return await RequestAsync<PagedResultDto<LookupDto<Guid>>>(nameof(GetProvinceLookupAsync), new ClientProxyRequestTypeValue
        {
            { typeof(LookupRequestDto), input }
        });
    }

    public virtual async Task<PagedResultDto<LookupDto<Guid>>> GetWardLookupAsync(LookupRequestDto input)
    {
        return await RequestAsync<PagedResultDto<LookupDto<Guid>>>(nameof(GetWardLookupAsync), new ClientProxyRequestTypeValue
        {
            { typeof(LookupRequestDto), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PlaceDto> CreateAsync(PlaceCreateDto input)
    {
        return await RequestAsync<PlaceDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PlaceCreateDto), input }
        });
    }

    public virtual async Task<PlaceDto> UpdateAsync(Guid id, PlaceUpdateDto input)
    {
        return await RequestAsync<PlaceDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(PlaceUpdateDto), input }
        });
    }

    public virtual async Task<IRemoteStreamContent> GetListAsExcelFileAsync(PlaceExcelDownloadDto input)
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(GetListAsExcelFileAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PlaceExcelDownloadDto), input }
        });
    }

    public virtual async Task DeleteByIdsAsync(List<Guid> placeIds)
    {
        await RequestAsync(nameof(DeleteByIdsAsync), new ClientProxyRequestTypeValue
        {
            { typeof(List<Guid>), placeIds }
        });
    }

    public virtual async Task DeleteAllAsync(GetPlacesInput input)
    {
        await RequestAsync(nameof(DeleteAllAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetPlacesInput), input }
        });
    }

    public virtual async Task<DownloadTokenResultDto> GetDownloadTokenAsync()
    {
        return await RequestAsync<DownloadTokenResultDto>(nameof(GetDownloadTokenAsync));
    }
}
