// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using KHHub.MasterDataService.Services.Dtos.PlaceTags;
using KHHub.MasterDataService.Services.Dtos.Shared;
using KHHub.MasterDataService.Services.PlaceTags;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Content;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace KHHub.MasterDataService.Services.PlaceTags;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IPlaceTagsAppService), typeof(PlaceTagsClientProxy))]
public partial class PlaceTagsClientProxy : ClientProxyBase<IPlaceTagsAppService>, IPlaceTagsAppService
{
    public virtual async Task<PagedResultDto<PlaceTagDto>> GetListAsync(GetPlaceTagsInput input)
    {
        return await RequestAsync<PagedResultDto<PlaceTagDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetPlaceTagsInput), input }
        });
    }

    public virtual async Task<PlaceTagDto> GetAsync(Guid id)
    {
        return await RequestAsync<PlaceTagDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PlaceTagDto> CreateAsync(PlaceTagCreateDto input)
    {
        return await RequestAsync<PlaceTagDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PlaceTagCreateDto), input }
        });
    }

    public virtual async Task<PlaceTagDto> UpdateAsync(Guid id, PlaceTagUpdateDto input)
    {
        return await RequestAsync<PlaceTagDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(PlaceTagUpdateDto), input }
        });
    }

    public virtual async Task<IRemoteStreamContent> GetListAsExcelFileAsync(PlaceTagExcelDownloadDto input)
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(GetListAsExcelFileAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PlaceTagExcelDownloadDto), input }
        });
    }

    public virtual async Task DeleteByIdsAsync(List<Guid> placetagIds)
    {
        await RequestAsync(nameof(DeleteByIdsAsync), new ClientProxyRequestTypeValue
        {
            { typeof(List<Guid>), placetagIds }
        });
    }

    public virtual async Task DeleteAllAsync(GetPlaceTagsInput input)
    {
        await RequestAsync(nameof(DeleteAllAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetPlaceTagsInput), input }
        });
    }

    public virtual async Task<DownloadTokenResultDto> GetDownloadTokenAsync()
    {
        return await RequestAsync<DownloadTokenResultDto>(nameof(GetDownloadTokenAsync));
    }
}
