using KHHub.MasterDataService.Services.Dtos.Shared;
using KHHub.MasterDataService.Entities.Provinces;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using KHHub.MasterDataService.Permissions;
using KHHub.MasterDataService.Services.Wards;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using KHHub.MasterDataService.Entities.Wards;
using KHHub.MasterDataService.Services.Dtos.Wards;
using KHHub.MasterDataService.Data.Wards;
using KHHub.MasterDataService.Services.Dtos.Shared;

namespace KHHub.MasterDataService.Services.Wards;

public class WardsAppService : WardsAppServiceBase, IWardsAppService
{
    //<suite-custom-code-autogenerated>
    public WardsAppService(IWardRepository wardRepository, WardManager wardManager, IDistributedCache<WardDownloadTokenCacheItem, string> downloadTokenCache, IRepository<KHHub.MasterDataService.Entities.Provinces.Province, Guid> provinceRepository) : base(wardRepository, wardManager, downloadTokenCache, provinceRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}